### ISSUE TITLE
update_all.py更新数据时  'ascii' codec can't encode characters in position 22-29: ordinal not in range(128)

### ISSUE THREAD

**Issue by hegphegp** [yutiansut/QUANTAXIS#1007]
# 问题反馈
##### 操作环境
* 使用的QUANTAXIS版本是docker-compose部署的docker版本
* 操作系统分别是Ubuntu-18.04和Centos-7.5
* docker软件版本是18.09
* docker安装的mongo镜像版本是3.4.5

## update_all.py更新数据时，抛错了，具体的异常信息是
```
QUANTAXIS>> ##JOB08 Now Saving STOCK_LIST ====
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/logging/__init__.py", line 994, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 22-29: ordinal not in range(128)
Call stack:
  File "/QUANTAXIS/config/update_all.py", line 51, in <module>
    QA_SU_save_stock_list('tdx')
  File "/QUANTAXIS/QUANTAXIS/QASU/main.py", line 75, in QA_SU_save_stock_list
    engine.QA_SU_save_stock_list(client=client)
  File "/QUANTAXIS/QUANTAXIS/QASU/save_tdx.py", line 1150, in QA_SU_save_stock_list
    ui_progress_int_value=10000
  File "/QUANTAXIS/QUANTAXIS/QAUtil/QALogs.py", line 126, in QA_util_log_info
    logging.warning(logs)
Message: '\u5b8c\u6210\u80a1\u7968\u5217\u8868\u83b7\u53d6'
Arguments: ()
QUANTAXIS>> \u5b8c\u6210\u80a1\u7968\u5217\u8868\u83b7\u53d6
QUANTAXIS>> ##JOB09 Now Saving STOCK_BlOCK ====
QUANTAXIS>> tdx Block ====
QUANTAXIS>> ths Block ====
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/logging/__init__.py", line 994, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 22-29: ordinal not in range(128)
Call stack:
  File "/QUANTAXIS/config/update_all.py", line 52, in <module>
    QA_SU_save_stock_block('tdx')
  File "/QUANTAXIS/QUANTAXIS/QASU/main.py", line 323, in QA_SU_save_stock_block
    engine.QA_SU_save_stock_block(client=client)
  File "/QUANTAXIS/QUANTAXIS/QASU/save_tdx.py", line 1202, in QA_SU_save_stock_block
    ui_progress_int_value=10000
  File "/QUANTAXIS/QUANTAXIS/QAUtil/QALogs.py", line 126, in QA_util_log_info
    logging.warning(logs)
Message: '\u5b8c\u6210\u80a1\u7968\u677f\u5757\u83b7\u53d6='
Arguments: ()
QUANTAXIS>> \u5b8c\u6210\u80a1\u7968\u677f\u5757\u83b7\u53d6=
```

#### 抛错截图
![image](https://user-images.githubusercontent.com/26202719/53678158-f1080700-3cf5-11e9-865d-88cab0c768bd.png)

#### 您的联系方式(QQ/EMAIL)
```
2386824052@qq.com
```

**Comment by zhongjyyy** [comment]
echo "\u5b8c\u6210\u80a1\u7968\u5217\u8868\u83b7\u53d6" ==> "完成股票列表获取"
报错的前段是日志错误
提示 UnicodeEncodeError: 'ascii' codec can't encode characters in position 22-29: ordinal not in range(128)
检查你自己的运行环境是否支持utf8

**Comment by hegphegp** [comment]
谢谢，是系统编码有问题。
