### ISSUE TITLE
ubuntu跑quantaxis_webserver出现 AttributeError: module 'tornado.wsgi' has no attribute 'WSGIApplication'

### ISSUE THREAD

**Issue by sixuerain** [yutiansut/QUANTAXIS#1069]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?
vnpy@ubuntu:~/anaconda3/bin$ quantaxis
QUANTAXIS> version
QUANTAXIS>> 1.3.4
```



```
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
```





```

## 您的系统环境是什么?
ubuntu 16.04 
```
- monodb
- nodejs(V9以下版本)
- python3.5/3.6
- docker(有无)
```
## 您需要反馈的问题
```

$quantaxis_webserver 
Traceback (most recent call last):
  File "/home/vnpy/anaconda3/bin/quantaxis_webserver", line 7, in <module>
    from QAWebServer.QA_Web import main
  File "/home/vnpy/anaconda3/lib/python3.6/site-packages/QAWebServer/__init__.py", line 26, in <module>
    from QAWebServer.datahandles import StockdayHandler, StockminHandler, DataFetcher
  File "/home/vnpy/anaconda3/lib/python3.6/site-packages/QAWebServer/datahandles.py", line 44, in <module>
    from QAWebServer.basehandles import QABaseHandler
  File "/home/vnpy/anaconda3/lib/python3.6/site-packages/QAWebServer/basehandles.py", line 430, in <module>
    class QAWSGIRestService(tornado.wsgi.WSGIApplication):
AttributeError: module 'tornado.wsgi' has no attribute 'WSGIApplication'
```
## 感谢您的反馈 如有意见和建议,请在此说明:
```



```
## 您的联系方式(QQ/EMAIL)
```

```

THANKS
by yutiansut
2017.12

**Comment by sixuerain** [comment]
==>
重装下tornado
=<
pip uninstall tornado 也试过了
==>
tornado 5.1.1
=<
噢，我是装的6.0.2
=<
ok, 5.1.1 work

**Comment by yutiansut** [comment]
先限定tornado 的版本 后面会补上
