### ISSUE TITLE
loading ip list from /Users/amu/.quantaxis/log/future_ip_list_MP.pickle. ALL IP PING TIMEOUT!

### ISSUE THREAD

**Issue by weidage** [yutiansut/QUANTAXIS#1070]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?

1.3.4

```
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)

mac os 64位




```

## 您的系统环境是什么?
```
- monodb
- python3.7
- docker有
```
## 您需要反馈的问题
```
QUANTAXIS>> === The BEST SERVER ===
 stock_ip None future_ip None
QUANTAXIS>> Selecting the Best Server IP of TDX
loading ip list from /Users/amu/.quantaxis/log/stock_ip_list_MP.pickle.
ALL IP PING TIMEOUT!
loading ip list from /Users/amu/.quantaxis/log/future_ip_list_MP.pickle.
ALL IP PING TIMEOUT!
QUANTAXIS>> === The BEST SERVER ===
 stock_ip None future_ip None
Traceback (most recent call last):
  File "/Users/amu/PycharmProjects/pytho2/craw/QTest.py", line 3, in <module>
    QA.QA_fetch_get_stock_list('tdx')
  File "/usr/local/lib/python3.7/site-packages/QUANTAXIS/QAFetch/__init__.py", line 158, in QA_fetch_get_stock_list
    return Engine.QA_fetch_get_stock_list(type_)
  File "/usr/local/lib/python3.7/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/local/lib/python3.7/site-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/usr/local/lib/python3.7/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/local/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/usr/local/lib/python3.7/site-packages/QUANTAXIS/QAFetch/QATdx.py", line 580, in QA_fetch_get_stock_list
    with api.connect(ip, port):
  File "/usr/local/lib/python3.7/site-packages/pytdx/base_socket_client.py", line 168, in connect
    log.debug("connecting to server : %s on port :%d" % (ip, port))
TypeError: %d format: a number is required, not NoneType

```
## 感谢您的反馈 如有意见和建议,请在此说明:
```



```
## 您的联系方式(QQ/EMAIL)
```

```

THANKS
by yutiansut
2017.12

**Comment by yutiansut** [comment]
pip install quantaxis==1.3.4

rm -rf /Users/amu/.quantaxis/log/future_ip_list_MP.pickle
