### ISSUE TITLE
Cannot import QA_Account

### ISSUE THREAD

**Issue by huduyi** [yutiansut/QUANTAXIS#1152]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?

```

1.4.9


```
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
```

系统版本：	macOS 10.13.6 (17G6030)
  内核版本：	Darwin 17.7.0
  启动宗卷：	Macintosh HD
处理器名称：	Intel Core i7
  处理器速度：	2.6 GHz
  处理器数目：	1
  核总数：	6
  L2 缓存（每个核）：	256 KB
  L3 缓存：	9 MB
  内存：	16 GB


```

## 您的系统环境是什么?
```
- monodb
- nodejs(V9以下版本)
- python3.5/3.6
- docker(有无)
```
## 您需要反馈的问题
```
无法启动 quantaxis，无法 import QA_Account

Traceback (most recent call last):
  File "/usr/local/opt/pyenv/versions/anaconda3-2019.03/bin/quantaxis", line 11, in <module>
    load_entry_point('quantaxis', 'console_scripts', 'quantaxis')()
  File "/usr/local/opt/pyenv/versions/anaconda3-2019.03/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/opt/pyenv/versions/anaconda3-2019.03/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/local/opt/pyenv/versions/anaconda3-2019.03/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/local/opt/pyenv/versions/anaconda3-2019.03/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/huchen/Software/quantaxis/QUANTAXIS/__init__.py", line 46, in <module>
    from QUANTAXIS.QAApplication.QABacktest import QA_Backtest
  File "/Users/huchen/Software/quantaxis/QUANTAXIS/QAApplication/QABacktest.py", line 28, in <module>
    from QUANTAXIS.QAARP.QAPortfolio import QA_Portfolio
  File "/Users/huchen/Software/quantaxis/QUANTAXIS/QAARP/__init__.py", line 25, in <module>
    from QUANTAXIS.QAARP.QAAccount import QA_Account
  File "/Users/huchen/Software/quantaxis/QUANTAXIS/QAARP/QAAccount.py", line 36, in <module>
    from QUANTAXIS.QAMarket.QAOrder import QA_Order, QA_OrderQueue
  File "/Users/huchen/Software/quantaxis/QUANTAXIS/QAMarket/__init__.py", line 32, in <module>
    from QUANTAXIS.QAMarket.QAMarket import QA_Market
  File "/Users/huchen/Software/quantaxis/QUANTAXIS/QAMarket/QAMarket.py", line 31, in <module>
    from QUANTAXIS.QAARP.QAAccount import QA_Account
ImportError: cannot import name 'QA_Account' from 'QUANTAXIS.QAARP.QAAccount' (/Users/huchen/Software/quantaxis/QUANTAXIS/QAARP/QAAccount.py)
```
## 感谢您的反馈 如有意见和建议,请在此说明:
```



```
## 您的联系方式(QQ/EMAIL)
```
416062563
```

THANKS
by yutiansut
2017.12

**Comment by yutiansut** [comment]
@huduyi


already fixed in https://github.com/QUANTAXIS/QUANTAXIS/pull/1158

please update to lastest version

````
pip install quantaxis==1.5.1
```

or 

```
cd quantaxis
git pull
pip install -e .
```
