### ISSUE TITLE
async_timeout & dependency on talib

### ISSUE THREAD

**Issue by ioiopp** [yutiansut/QUANTAXIS#1163]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?

```

1.5.1

```
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
```

win 10 64 8g



```

## 您的系统环境是什么?
```
- monodb
- nodejs(V9以下版本)
- python3.5/**3.6**
- docker(有无)
```
## 您需要反馈的问题
```
I created a conda env quantaxis with python 3.6.8 and then installed 1.5.1. Two issues encountered:

1. **PLEASE install TALIB to call these methods**
2. **ModuleNotFoundError: No module named 'async_timeout'**

Could you kindly take a look? thx

(quantaxis) C:\Users\ioiop>python
Python 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import QUANTAXIS as QA
**PLEASE install TALIB to call these methods
PLEASE install TALIB to call these methods**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "G:\ProgramData\VNConda\envs\quantaxis\lib\site-packages\QUANTAXIS\__init__.py", line 46, in <module>
    from QUANTAXIS.QAApplication.QABacktest import QA_Backtest
  File "G:\ProgramData\VNConda\envs\quantaxis\lib\site-packages\QUANTAXIS\QAApplication\QABacktest.py", line 29, in <module>
    from QUANTAXIS.QAARP.QAUser import QA_User
  File "G:\ProgramData\VNConda\envs\quantaxis\lib\site-packages\QUANTAXIS\QAARP\__init__.py", line 25, in <module>
    from QUANTAXIS.QAARP.QAAccount import QA_Account
  File "G:\ProgramData\VNConda\envs\quantaxis\lib\site-packages\QUANTAXIS\QAARP\QAAccount.py", line 35, in <module>
    from QUANTAXIS.QAEngine.QAEvent import QA_Worker
  File "G:\ProgramData\VNConda\envs\quantaxis\lib\site-packages\QUANTAXIS\QAEngine\__init__.py", line 29, in <module>
    from QUANTAXIS.QAEngine.QAAsyncExec import QA_AsyncExec
  File "G:\ProgramData\VNConda\envs\quantaxis\lib\site-packages\QUANTAXIS\QAEngine\QAAsyncExec.py", line 6, in <module>
    from QUANTAXIS.QAEngine.QAAsyncSchedule import create_QAAsyncScheduler
  File "G:\ProgramData\VNConda\envs\quantaxis\lib\site-packages\QUANTAXIS\QAEngine\QAAsyncSchedule.py", line 4, in <module>
    from QUANTAXIS.QAEngine.QAAsyncTask import QA_AsyncTask
  File "G:\ProgramData\VNConda\envs\quantaxis\lib\site-packages\QUANTAXIS\QAEngine\QAAsyncTask.py", line 6, in <module>
    import async_timeout
**ModuleNotFoundError: No module named 'async_timeout'**

```
## 感谢您的反馈 如有意见和建议,请在此说明:
```



```
## 您的联系方式(QQ/EMAIL)
```
ioiopp@163.com
```

THANKS
by yutiansut
2017.12

**Comment by yutiansut** [comment]
pip install async_timeout @ioiopp

**Comment by yutiansut** [comment]
talib is not a essential option for QUANTAXIS, if U are using Talib, QUANTAXIS gave a integrated option, however if U have never used talib, just ignore the tips

if U want to install talib on win/linux, go to
https://github.com/QUANTAXIS/QUANTAXIS/issues/379#issuecomment-395978229
to find the methods

**Comment by ioiopp** [comment]
> pip install async_timeout @ioiopp

would be better to add to the requirements?

**Comment by yutiansut** [comment]
> > pip install async_timeout @ioiopp
> 
> would be better to add to the requirements?

yep, its already in the next verion's requirements:

see https://github.com/QUANTAXIS/QUANTAXIS/blob/master/setup.py#L111
