### ISSUE TITLE
qadesktop获取数据为日线频率时出错500

### ISSUE THREAD

**Issue by luohan475947645** [yutiansut/QUANTAXIS#1419]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?

```
1.8.0
```
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
```
ubuntu18.04
```

## 您的系统环境是什么?
```
- docker版本
```
## 您需要反馈的问题

使用docker版本的建立的环境。desktop界面获取分钟级数据正常，获取日线数据时出现出错误。
![image](https://user-images.githubusercontent.com/35267208/73592750-68629e00-4538-11ea-9ff3-2ed096984f01.png)
![image](https://user-images.githubusercontent.com/35267208/73592895-2cc8d380-453a-11ea-8fe3-6c4a69120d7b.png)

单独请求该url时堆栈信息
![image](https://user-images.githubusercontent.com/35267208/73592765-95af4c00-4538-11ea-97cd-1e12d3fef8be.png)
查看源码应该是函数使用的问题`/QAWebServer/quotationhandles.py.stock_realtime`中使用的函数，当frequency不是分钟级别时，该函数取不到数据
![image](https://user-images.githubusercontent.com/35267208/73592805-1d955600-4539-11ea-9268-d2e20c843d48.png)

```
In[16]: res = QA.QA_fetch_get_stock_min('tdx', symbol, start, end, frequence)
Traceback (most recent call last):
  File "/home/hfin/.conda/envs/rqqa/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-16-6a9907e09e05>", line 1, in <module>
    res = QA.QA_fetch_get_stock_min('tdx', symbol, start, end, frequence)
  File "/home/hfin/.conda/envs/rqqa/lib/python3.7/site-packages/QUANTAXIS/QAFetch/__init__.py", line 96, in QA_fetch_get_stock_min
    return Engine.QA_fetch_get_stock_min(code, start, end, level)
  File "/home/hfin/.conda/envs/rqqa/lib/python3.7/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/home/hfin/.conda/envs/rqqa/lib/python3.7/site-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/home/hfin/.conda/envs/rqqa/lib/python3.7/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/home/hfin/.conda/envs/rqqa/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/hfin/.conda/envs/rqqa/lib/python3.7/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/home/hfin/.conda/envs/rqqa/lib/python3.7/site-packages/QUANTAXIS/QAFetch/QATdx.py", line 417, in QA_fetch_get_stock_min
    inplace=False) \
  File "/home/hfin/.conda/envs/rqqa/lib/python3.7/site-packages/pandas/core/frame.py", line 3940, in drop
    errors=errors)
  File "/home/hfin/.conda/envs/rqqa/lib/python3.7/site-packages/pandas/core/generic.py", line 3780, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/home/hfin/.conda/envs/rqqa/lib/python3.7/site-packages/pandas/core/generic.py", line 3812, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "/home/hfin/.conda/envs/rqqa/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 4965, in drop
    '{} not found in axis'.format(labels[mask]))
KeyError: "['year' 'month' 'day' 'hour' 'minute'] not found in axis"
```
## 感谢您的反馈 如有意见和建议,请在此说明:
```



```
## 您的联系方式(QQ/EMAIL)
```

```

THANKS
by yutiansut
2017.12

**Comment by yutiansut** [comment]
哦 日线这个的web接口我没写 所以你请求是没有的

**Comment by luohan475947645** [comment]
嗯，偶然读到，这个也不影响使用
