### ISSUE TITLE
关于realtimecollector推送接收的使用，订阅不到数据

### ISSUE THREAD

**Issue by luohan475947645** [yutiansut/QUANTAXIS#1448]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?

```
1.8.0
```
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
```
docker版本
```

## 您的系统环境是什么?
```
- monodb
- nodejs(V9以下版本)
- python3.5/3.6
- docker(有无)
```
## 您需要反馈的问题
`股票的realtimecollector原理是什么样的，我看代码一直没搞懂发布到哪个exchange中，又该如何订阅。有没有详细的文档说明下构建过程。`
我按照教程，先发送post请求，结果显示"success"
```
http://localhost:8011?action=new_handler&market_type=stock_cn&code=000001
```

然后在终端使用命令接收，没有反应
```
qaps_sub --exchange stocktransaction --model fanout
```
![image](https://user-images.githubusercontent.com/35267208/74300542-12d58f00-4d8b-11ea-850a-eec2d03da8f3.png)

所以这些订阅，发布的exchange到底是如何命名，分别是哪些类发起的推送。

运行QAStrategy.exsample下的Stock_Example.py文件报错。它的subscribe_data中订阅的exchange是在realtimecollector的哪个部分发布的呢
```
        self.sub = subscriber_topic(exchange='realtime_stock_{}'.format(
            frequence), host=data_host, port=data_port, user=data_user, password=data_password, routing_key='')
        for item in code:
            self.sub.add_sub(exchange='realtime_stock_{}'.format(
                frequence), routing_key=item)
        self.sub.callback = self.callback
```
```python
QUANTAXIS>> Received remote Channel.Close (406): "PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'realtime_stock_1min' in vhost '/': received 'topic' but current is 'fanout'" on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f79c0f443d0> params=<ConnectionParameters host=127.0.0.1 port=5672 virtual_host=/ ssl=False>>>
Traceback (most recent call last):
  File "/home/hfin/aiproject/aidata/exsampleQA/6_QAStrategy/Stock_Example.py", line 29, in <module>
    s.run_sim()
  File "/home/hfin/aiproject/aidata/aidata/QAStrategy/qactabase.py", line 149, in run_sim
    self._debug_sim()
  File "/home/hfin/aiproject/aidata/aidata/QAStrategy/qastockbase.py", line 143, in _debug_sim
    self.data_port, self.data_user, self.data_password)
  File "/home/hfin/aiproject/aidata/aidata/QAStrategy/qastockbase.py", line 54, in subscribe_data
    frequence), host=data_host, port=data_port, user=data_user, password=data_password, routing_key='')
  File "/home/hfin/.conda/envs/rqqa/lib/python3.7/site-packages/QAPUBSUB/consumer.py", line 119, in __init__
    auto_delete=False)
  File "/home/hfin/.conda/envs/rqqa/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 2442, in exchange_declare
    self._flush_output(declare_ok_result.is_ready)
  File "/home/hfin/.conda/envs/rqqa/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 1350, in _flush_output
    raise self._closing_reason  # pylint: disable=E0702
pika.exceptions.ChannelClosedByBroker: (406, "PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'realtime_stock_1min' in vhost '/': received 'topic' but current is 'fanout'")
```

## 感谢您的反馈 如有意见和建议,请在此说明:
```



```
## 您的联系方式(QQ/EMAIL)
```

```

THANKS
by yutiansut
2017.12

**Comment by yutiansut** [comment]
自己乱写 把属性写错了呗...
