### ISSUE TITLE
import QUANTAXIS as QA直接报错

### ISSUE THREAD

**Issue by ifdandy** [yutiansut/QUANTAXIS#1512]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?

```

__version__ = '1.9.14'

```
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
```

win10, 64, 4G



```

## 您的系统环境是什么?
```
- monodb
- nodejs(V9以下版本)
- python3.6
- docker(无)
```
## 您需要反馈的问题
```
import QUANTAXIS as QA
print(QA.__version__)

----------->>>>>>>>>>>>>>

C:\Anaconda3\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
Traceback (most recent call last):
  File "C:/pydemo/QUANTAXIS-master/config/update_data.py", line 3, in <module>
    import QUANTAXIS as QA
  File "C:\pydemo\QUANTAXIS-master\QUANTAXIS\__init__.py", line 281, in <module>
    from QUANTAXIS.QAFactor.analyze import FactorAnalyzer
  File "C:\pydemo\QUANTAXIS-master\QUANTAXIS\QAFactor\__init__.py", line 25, in <module>
    from QUANTAXIS.QAFactor.analyze import FactorAnalyzer
  File "C:\pydemo\QUANTAXIS-master\QUANTAXIS\QAFactor\analyze.py", line 12, in <module>
    from QUANTAXIS.QAFactor import performance as perf
  File "C:\pydemo\QUANTAXIS-master\QUANTAXIS\QAFactor\performance.py", line 12, in <module>
    from statsmodels.api import OLS, add_constant
  File "C:\Anaconda3\lib\site-packages\statsmodels\api.py", line 16, in <module>
    from .tsa import api as tsa
  File "C:\Anaconda3\lib\site-packages\statsmodels\tsa\api.py", line 24, in <module>
    from .regime_switching.markov_regression import MarkovRegression
  File "C:\Anaconda3\lib\site-packages\statsmodels\tsa\regime_switching\markov_regression.py", line 13, in <module>
    from statsmodels.tsa.regime_switching import markov_switching
  File "C:\Anaconda3\lib\site-packages\statsmodels\tsa\regime_switching\markov_switching.py", line 15, in <module>
    from scipy.misc import logsumexp
ImportError: cannot import name 'logsumexp'
```
## 感谢您的反馈 如有意见和建议,请在此说明:
```



```
## 您的联系方式(QQ/EMAIL)
```
Q:2335563089
```

THANKS
by yutiansut
2017.12

**Comment by ifdandy** [comment]
scipy降级到1.2.1就没问题了
