### ISSUE TITLE
获取数据接口error  AttributeError: __enter__

### ISSUE THREAD

**Issue by john012343210** [yutiansut/QUANTAXIS#1545]
# 问题反馈

## 您使用的QUANTAXIS版本号是什么?
'1.9.24'
## 系统？
win10
python 3.7.6

## 问题？

很多获取数据的接口发生这个问题
```



~\AppData\Roaming\Python\Python37\site-packages\QUANTAXIS\QAFetch\QATdx.py in QA_fetch_get_extensionmarket_list(ip, port)
   1417     ip, port = get_extensionmarket_ip(ip, port)
   1418     apix = TdxExHq_API()
-> 1419     with apix.connect(ip, port):
   1420         num = apix.get_instrument_count()
   1421         return pd.concat([apix.to_df(

AttributeError: __enter__

**Comment by yutiansut** [comment]
网络不好 重试即可

**Comment by liwendong66** [comment]
股票数据获取正常，期货获取不到数据啊
>>> QA.QAFetch.QATdx.QA_fetch_get_future_min('RB1905','2019-01-01','2019-01-30', '5min')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/hulongfei/PycharmPro/QUANTAXIS/QUANTAXIS/QAFetch/QATdx.py", line 2422, in QA_fetch_get_future_min
    ) if extension_market_list is None else extension_market_list
  File "/Users/hulongfei/PycharmPro/QUANTAXIS/QUANTAXIS/QAFetch/QATdx.py", line 1427, in QA_fetch_get_extensionmarket_list
    with apix.connect(ip, port):
AttributeError: __enter__

**Comment by yutiansut** [comment]
@liwendong66 1905已经退市 本来也获取不到
