### ISSUE TITLE
save all报错啦

### ISSUE THREAD

**Issue by markqiu** [yutiansut/QUANTAXIS#1548]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?

```
最新的，今天刚刚安装的docker版


```
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
```

ubuntu18.04



```

## 您的系统环境是什么?
```
- docker
```
## 您需要反馈的问题
```
进入client后，运行save all报错如下：
QUANTAXIS> save all
QUANTAXIS>> Selecting the Best Server IP of TDX
BAD RESPONSE 119.147.171.206
DEFAULT STOCK IP is BAD, RETESTING
BAD RESPONSE 106.120.74.86
BAD RESPONSE 221.194.181.176
BAD RESPONSE 114.80.80.222
BAD RESPONSE 114.80.80.222
BAD RESPONSE 117.184.140.156
BAD RESPONSE 119.147.171.206
BAD RESPONSE 119.147.171.206
BAD RESPONSE 121.14.2.7
Progress: 5.00%
Progress: 10.00%
BAD RESPONSE 113.105.73.88
BAD RESPONSE 113.105.73.88
Progress: 15.00%
BAD RESPONSE 218.108.50.178
Progress: 20.00%
BAD RESPONSE 112.95.140.92
BAD RESPONSE 112.95.140.74
BAD RESPONSE 112.95.140.93
BAD RESPONSE 113.05.73.88
BAD RESPONSE 114.80.149.84
Progress: 25.00%
Progress: 30.00%
Progress: 35.00%
BAD RESPONSE 119.29.51.30
BAD RESPONSE 121.14.104.70
BAD RESPONSE 121.14.104.72
BAD RESPONSE 121.14.110.194
Progress: 40.00%
BAD RESPONSE hq1.daton.com.cn
BAD RESPONSE 180.153.18.17
Progress: 45.00%
BAD RESPONSE 218.108.50.178
Progress: 50.00%
BAD RESPONSE 218.9.148.108
BAD RESPONSE 59.173.18.69
Progress: 55.00%
BAD RESPONSE 60.28.29.69
BAD RESPONSE 61.135.142.73
BAD RESPONSE 61.135.142.88
Progress: 60.00%
BAD RESPONSE 61.152.107.168
BAD RESPONSE 61.153.144.179
Progress: 65.00%
BAD RESPONSE 61.153.209.139
BAD RESPONSE 23.129.245.199
Progress: 70.00%
Progress: 75.00%
saving ip list to stock cache 28
USING DEFAULT FUTURE IP
QUANTAXIS>> === The BEST SERVER ===
 stock_ip 119.147.171.206 future_ip 139.219.103.190
Traceback (most recent call last):
  File "/usr/local/bin/quantaxis", line 11, in <module>
    sys.exit(QA_cmd())
  File "/usr/local/lib/python3.6/site-packages/QUANTAXIS/QACmd/__init__.py", line 650, in QA_cmd
    cli.cmdloop()
  File "/usr/local/lib/python3.6/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/local/lib/python3.6/cmd.py", line 217, in onecmd
    return func(arg)
  File "/usr/local/lib/python3.6/site-packages/QUANTAXIS/QACmd/__init__.py", line 342, in do_save
    QA_SU_save_stock_day('tdx')
  File "/usr/local/lib/python3.6/site-packages/QUANTAXIS/QAUtil/__init__.py", line 169, in wrapper
    func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/QUANTAXIS/QASU/main.py", line 222, in QA_SU_save_stock_day
    engine.QA_SU_save_stock_day(client=client)
  File "/usr/local/lib/python3.6/site-packages/QUANTAXIS/QASU/save_tdx.py", line 190, in QA_SU_save_stock_day
    stock_list = QA_fetch_get_stock_list().code.unique().tolist()
  File "/usr/local/lib/python3.6/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/local/lib/python3.6/site-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/usr/local/lib/python3.6/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/local/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/usr/local/lib/python3.6/site-packages/QUANTAXIS/QAFetch/QATdx.py", line 700, in QA_fetch_get_stock_list
    with api.connect(ip, port):
  File "/usr/local/lib/python3.6/site-packages/pytdx/base_socket_client.py", line 189, in connect
    self.setup()
  File "/usr/local/lib/python3.6/site-packages/pytdx/hq.py", line 53, in setup
    SetupCmd1(self.client).call_api()
  File "/usr/local/lib/python3.6/site-packages/pytdx/parser/base.py", line 74, in call_api
    result = self._call_api()
  File "/usr/local/lib/python3.6/site-packages/pytdx/parser/base.py", line 147, in _call_api
    raise ResponseHeaderRecvFails("head_buf is not 0x10 : " + str(head_buf))
pytdx.parser.base.ResponseHeaderRecvFails: head_buf is not 0x10 : b''

```
## 感谢您的反馈 如有意见和建议,请在此说明:
```
重装过pytdx了，还是不行


```
## 您的联系方式(QQ/EMAIL)
```
qiucheng@jinniuai.com
```

THANKS
by yutiansut
2017.12

**Comment by markqiu** [comment]
重装了一下pytdx就好了
