### ISSUE TITLE
更新历史行情数据时，出现 KeyError: 'code' 错误

### ISSUE THREAD

**Issue by gzMichael** [yutiansut/QUANTAXIS#1568]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?

```
1.9.11


```
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
```
Ubuntu / Win 均出现错误

```

## 您的系统环境是什么?
```
- monodb v4.0.10
- pytho3.6
- 无 docker
```

## 您需要反馈的问题
```
QUANTAXIS> save all
QUANTAXIS>> Selecting the Best Server IP of TDX
USING DEFAULT STOCK IP
USING DEFAULT FUTURE IP
QUANTAXIS>> === The BEST SERVER ===
 stock_ip sztdx.gtjas.com future_ip 59.175.238.38
Traceback (most recent call last):
  File "d:\anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 2657,
in get_loc
    return self._engine.get_loc(key)
  File "pandas\_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get
_loc
  File "pandas\_libs\index.pyx", line 132, in pandas._libs.index.IndexEngine.get
_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1601, in pandas._libs.has
htable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1608, in pandas._libs.has
htable.PyObjectHashTable.get_item
KeyError: 'code'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "d:\Anaconda3\Scripts\quantaxis.exe\__main__.py", line 9, in <module>
  File "d:\anaconda3\lib\site-packages\QUANTAXIS\QACmd\__init__.py", line 632, i
n QA_cmd
    cli.cmdloop()
  File "d:\anaconda3\lib\cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "d:\anaconda3\lib\cmd.py", line 217, in onecmd
    return func(arg)
  File "d:\anaconda3\lib\site-packages\QUANTAXIS\QACmd\__init__.py", line 329, i
n do_save
    QA_SU_save_stock_day('tdx')
  File "d:\anaconda3\lib\site-packages\QUANTAXIS\QAUtil\__init__.py", line 185,
in wrapper
    func(*args, **kwargs)
  File "d:\anaconda3\lib\site-packages\QUANTAXIS\QASU\main.py", line 195, in QA_
SU_save_stock_day
    engine.QA_SU_save_stock_day(client=client)
  File "d:\anaconda3\lib\site-packages\QUANTAXIS\QASU\save_tdx.py", line 187, in
 QA_SU_save_stock_day
    stock_list = QA_fetch_get_stock_list().code.unique().tolist()
  File "d:\anaconda3\lib\site-packages\retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "d:\anaconda3\lib\site-packages\retrying.py", line 212, in call
    raise attempt.get()
  File "d:\anaconda3\lib\site-packages\retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "d:\anaconda3\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "d:\anaconda3\lib\site-packages\retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "d:\anaconda3\lib\site-packages\QUANTAXIS\QAFetch\QATdx.py", line 707, in
 QA_fetch_get_stock_list
    in range(2)], axis=0, sort=False)
  File "d:\anaconda3\lib\site-packages\QUANTAXIS\QAFetch\QATdx.py", line 706, in
 <listcomp>
    j
  File "d:\anaconda3\lib\site-packages\QUANTAXIS\QAFetch\QATdx.py", line 704, in
 <listcomp>
    ['code', 'sse'], drop=False) for i in
  File "d:\anaconda3\lib\site-packages\pandas\core\frame.py", line 4178, in set_
index
    level = frame[col]._values
  File "d:\anaconda3\lib\site-packages\pandas\core\frame.py", line 2927, in __ge
titem__
    indexer = self.columns.get_loc(key)
  File "d:\anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 2659,
in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas\_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get
_loc
  File "pandas\_libs\index.pyx", line 132, in pandas._libs.index.IndexEngine.get
_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1601, in pandas._libs.has
htable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1608, in pandas._libs.has
htable.PyObjectHashTable.get_item
KeyError: 'code'


```

上周还可以正常使用，昨天发现更新会出现这个错误

**Comment by kaikai03** [comment]
quantaipxis到1.9.30

**Comment by gzMichael** [comment]
更新之后就可以了，谢谢
