### ISSUE TITLE
window 启动quantaxis_webserver报错 KeyError: "['_id'] not found in axis"

### ISSUE THREAD

**Issue by couldn** [yutiansut/QUANTAXIS#1574]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?

```最新



```
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
```

64



```

## 您的系统环境是什么?
```
- monodb
- nodejs(V9以下版本)
- python3.7.6
- docker(无)
```
## 您需要反馈的问题
```
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Zhang\AppData\Roaming\Python\Python37\Scripts\quantaxis_webserver.exe\__main__.py", line 4, in <module>
  File "C:\Users\Zhang\AppData\Roaming\Python\Python37\site-packages\QAWebServer\__init__.py", line 29, in <module>
    from QAWebServer.QA_Web import main
  File "C:\Users\Zhang\AppData\Roaming\Python\Python37\site-packages\QAWebServer\QA_Web.py", line 47, in <module>
    from QAWebServer.select_codehandler import SelectCodehandler
  File "C:\Users\Zhang\AppData\Roaming\Python\Python37\site-packages\QAWebServer\select_codehandler.py", line 5, in <module>
    class SelectCodehandler(QABaseHandler):
  File "C:\Users\Zhang\AppData\Roaming\Python\Python37\site-packages\QAWebServer\select_codehandler.py", line 18, in SelectCodehandler
    stocklist= QA.QA_fetch_stock_list_adv()
  File "C:\Users\Zhang\AppData\Roaming\Python\Python37\site-packages\QUANTAXIS\QAFetch\QAQuery_Advance.py", line 492, in QA_fetch_stock_list_adv
    stock_list_items = QA_fetch_stock_list(collections)
  File "C:\Users\Zhang\AppData\Roaming\Python\Python37\site-packages\QUANTAXIS\QAFetch\QAQuery.py", line 404, in QA_fetch_stock_list
    inplace=False
  File "C:\Users\Zhang\AppData\Roaming\Python\Python37\site-packages\pandas\core\frame.py", line 3940, in drop
    errors=errors)
  File "C:\Users\Zhang\AppData\Roaming\Python\Python37\site-packages\pandas\core\generic.py", line 3780, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "C:\Users\Zhang\AppData\Roaming\Python\Python37\site-packages\pandas\core\generic.py", line 3812, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "C:\Users\Zhang\AppData\Roaming\Python\Python37\site-packages\pandas\core\indexes\base.py", line 4965, in drop
    '{} not found in axis'.format(labels[mask]))
KeyError: "['_id'] not found in axis"

```
## 感谢您的反馈 如有意见和建议,请在此说明:
```



```
## 您的联系方式(QQ/EMAIL)
```

```

THANKS
by yutiansut
2017.12

**Comment by yutiansut** [comment]
存数据啊....... save stock_list @couldn

**Comment by kries2333** [comment]
> 存数据啊....... save stock_list @couldn
我的也是这个问题！
请问什么意思？是数据没导入吗？

**Comment by fsz168** [comment]
存数据啊？这个怎么操作？我也遇到这问题

**Comment by pleamon** [comment]
attach 到 qaweb
运行 quantaxis
运行 save all 或者 save stock_list
