### ISSUE TITLE
Python tornado 报错

### ISSUE THREAD

**Issue by WangEdward** [yutiansut/QUANTAXIS#1595]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?

```
1.9.30 Docker版
```
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
```
Debian，x64
```

## 您的系统环境是什么?
```
docker 一键部署
```
## 您需要反馈的问题
-在访问QACEPEngine的服务器地址时（8011端口），会有如下报错
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/root/QUANTAXIS_RealtimeCollector/QARealtimeCollector/webserver.py", line 27, in get
    action = self.get_argument('action')
  File "/usr/local/lib/python3.7/site-packages/tornado/web.py", line 407, in get_argument
    return self._get_argument(name, default, self.request.arguments, strip)
  File "/usr/local/lib/python3.7/site-packages/tornado/web.py", line 484, in _get_argument
    raise MissingArgumentError(name)
tornado.web.MissingArgumentError: HTTP 400: Bad Request (Missing argument action)
```

-在访问qatraderServer的服务器地址时（8020端口），会有如下报错
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/tornado/web.py", line 1569, in _execute
    result = self.prepare()
  File "/usr/local/lib/python3.6/site-packages/tornado/web.py", line 2322, in prepare
    raise HTTPError(self._status_code)
tornado.web.HTTPError: HTTP 404: Not Found
```

请问如何解决，感谢

**Comment by yutiansut** [comment]
无请求参数？

**Comment by WangEdward** [comment]
都是直接 get 请求 ip:port

**Comment by WangEdward** [comment]
![Uploading Screen Shot 2020-12-21 at 9.39.55 AM.png…]()

**Comment by WangEdward** [comment]
<img width="428" alt="Screen Shot 2020-12-21 at 9 39 55 AM" src="https://user-images.githubusercontent.com/73746306/102730801-e1492f00-4370-11eb-9e2d-648136ba3536.png">

**Comment by yutiansut** [comment]
@WangEdward tornado.web.MissingArgumentError: HTTP 400: Bad Request (Missing argument action) 这个错误的意思是你缺一个参数叫 action

**Comment by WangEdward** [comment]
请问如何解决呢，因为这是直接用 docker 部署的
