### ISSUE TITLE
从股票的docker-compose.yaml 切换到期货的提示pika.exceptions.AMQPConnectionError

### ISSUE THREAD

**Issue by newlyedward** [yutiansut/QUANTAXIS#1603]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?

```



```
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
```





```

## 您的系统环境是什么?
```
- monodb
- nodejs(V9以下版本)
- python3.5/3.6
- docker(有无)
```
## 您需要反馈的问题

qactpbeebroker运行失败退出
```
CONTAINER ID   IMAGE                                              COMMAND                  CREATED          STATUS                      PORTS                                                                                                                       NAMES
2a9d5247719f   daocloud.io/quantaxis/qactpbeebroker:latest        "/root/wait_for_it.s…"   33 minutes ago   **Exited (1)** 32 minutes ago                                                                                                                               quantaxis_docker_qactpbeebroker_1
```

[root@localhost quantaxis_docker]# docker logs 2a9d5247719f
```
wait_for_it.sh: waiting 15 seconds for qaeventmq:15672
wait_for_it.sh: timeout occurred after waiting 15 seconds for qaeventmq:15672
Traceback (most recent call last):
  File "/usr/local/bin/QACTPBEE", line 11, in <module>
    load_entry_point('QACTPBeeBroker', 'console_scripts', 'QACTPBEE')()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/root/QACTPBeeBroker/QACTPBeeBroker/__init__.py", line 94, in go
    data_recorder = DataRecorder("data_recorder")
  File "/root/QACTPBeeBroker/QACTPBeeBroker/__init__.py", line 19, in __init__
    self.pub = publisher_routing(host=eventmq_ip, exchange='CTPX', routing_key='')
  File "/usr/local/lib/python3.7/site-packages/QAPUBSUB/producer.py", line 57, in __init__
    queue_name, routing_key,  exchange, exchange_type, vhost)
  File "/usr/local/lib/python3.7/site-packages/QAPUBSUB/base.py", line 26, in __init__
    credentials=self.credentials, heartbeat=0, socket_timeout=5,
  File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 366, in __init__
    self._impl = self._create_connection(parameters, _impl_class)
  File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 458, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
**pika.exceptions.AMQPConnectionError**
注销
```

```
## 感谢您的反馈 如有意见和建议,请在此说明:
```

```
## 您的联系方式(QQ/EMAIL)
```

```


THANKS
by yutiansut
2017.12

**Comment by yutiansut** [comment]
检查你的eventmq的repo有没有拉起来

**Comment by newlyedward** [comment]
其他7个docker都可以正常使用，qaeventmq运行也没有问题，stocktransaction,QAAcoount这些exchangs都能在rabbitmq上看到。
[root@localhost ~]# docker ps -a
```
CONTAINER ID   IMAGE                                              COMMAND                  CREATED        STATUS                    PORTS                                                                                                                       NAMES
db769d6c10d4   daocloud.io/quantaxis/qactpbeebroker:latest        "/root/wait_for_it.s…"   22 hours ago   Exited (1) 11 hours ago                                                                                                                               quantaxis_docker_qactpbeebroker_1
fab67524bc82   yutiansut/ctpbee:latest                            "python /root/ctpbee…"   24 hours ago   Exited (0) 24 hours ago                                                                                                                               kind_mclean
7989446dd255   daocloud.io/quantaxis/qarealtimecollector:latest   "/root/QUANTAXIS_Rea…"   2 days ago     Up 11 hours               5000/tcp, 0.0.0.0:8011->8011/tcp                                                                                            quantaxis_docker_qamarketcollector_1
1c2bc6f63234   daocloud.io/quantaxis/qatrader:latest              "/root/QATrader/dock…"   2 days ago     Up 11 hours               8010/tcp, 0.0.0.0:8020->8020/tcp                                                                                            quantaxis_docker_qatrader_1
929535c4d5bf   daocloud.io/quantaxis/qarun:latest                 "/root/wait_for_it.s…"   2 days ago     Up 11 hours               0.0.0.0:8010->8010/tcp                                                                                                      qarun
feff3fa93d95   daocloud.io/quantaxis/qacommunity:latest           "bash /root/run-comm…"   2 days ago     Up 11 hours               0.0.0.0:8787->8787/tcp, 0.0.0.0:8888->8888/tcp, 0.0.0.0:81->80/tcp                                                          qacommunity
47be6e7f0cf1   daocloud.io/quantaxis/qaeditor:latest              "yarn theia start /h…"   2 days ago     Up 11 hours               0.0.0.0:3001->3000/tcp                                                                                                      qaeditor
a3cb7229e374   daocloud.io/quantaxis/qaeventmq:latest             "docker-entrypoint.s…"   11 days ago    Up 11 hours               0.0.0.0:4369->4369/tcp, 5671/tcp, 0.0.0.0:5672->5672/tcp, 15671/tcp, 15691-15692/tcp, 0.0.0.0:15672->15672/tcp, 25672/tcp   quantaxis_docker_qaeventmq_1
b0b6cdbd69b7   daocloud.io/quantaxis/qa-monitor:latest            "/bin/sh -c 'python …"   11 days ago    Up 11 hours               0.0.0.0:61208-61209->61208-61209/tcp                                                                                        quantaxis_docker_qamonitor_1


```

**Comment by yutiansut** [comment]
![image](https://user-images.githubusercontent.com/11537812/102716126-b8259180-42d1-11eb-81e7-a6bfd0185c14.png)
你这图谁能看懂？

**Comment by newlyedward** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/11537812/102716126-b8259180-42d1-11eb-81e7-a6bfd0185c14.png)
> 你这图谁能看懂
图看不到，文字修改了一下，就是除了CTP的功能QA都能用，web页面也能收到期货的实时行情，rabbitmq也能用。
