### ISSUE TITLE
quantaxis cli中执行save x和save all报错，盼复，非常感谢

### ISSUE THREAD

**Issue by chino1918** [yutiansut/QUANTAXIS#1654]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?
刚git pull的master分支，应该是最新版本吧

## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
win10/64 64G内存 

## 您的系统环境是什么?
```
- monodb
- python3.7/3.8
- docker(有)
```

## 您需要反馈的问题
**问题1：执行save all和save x时报如下错误：**
QUANTAXIS>> === The BEST SERVER ===
 stock_ip 121.14.110.194 future_ip 59.175.238.38
Traceback (most recent call last):
  File "/opt/conda/bin/quantaxis", line 8, in <module>
    sys.exit(QA_cmd())
  File "/opt/conda/lib/python3.8/site-packages/QUANTAXIS/QACmd/__init__.py", line 735, in QA_cmd
    cli.cmdloop()
  File "/opt/conda/lib/python3.8/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/opt/conda/lib/python3.8/cmd.py", line 217, in onecmd
    return func(arg)
  File "/opt/conda/lib/python3.8/site-packages/QUANTAXIS/QACmd/__init__.py", line 380, in do_save
    QA_SU_save_stock_day("tdx")
  File "/opt/conda/lib/python3.8/site-packages/QUANTAXIS/QAUtil/__init__.py", line 169, in wrapper
    func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/QUANTAXIS/QASU/main.py", line 222, in QA_SU_save_stock_day
    engine.QA_SU_save_stock_day(client=client)
  File "/opt/conda/lib/python3.8/site-packages/QUANTAXIS/QASU/save_tdx.py", line 196, in QA_SU_save_stock_day
    stock_list = QA_fetch_get_stock_list().code.unique().tolist()
  File "/opt/conda/lib/python3.8/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/opt/conda/lib/python3.8/site-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/opt/conda/lib/python3.8/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/opt/conda/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/lib/python3.8/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/opt/conda/lib/python3.8/site-packages/QUANTAXIS/QAFetch/QATdx.py", line 704, in QA_fetch_get_stock_list
    with api.connect(ip, port):
AttributeError: __enter__

**问题2. 81端口web页面登陆失败（卡在登录页，输入用户名和密码没有反应）**
看启动日志有如下报错，不知道是否是由于没有获取stock_list
[2021-02-06 10:44:27,166: INFO/MainProcess] celery@779aaebf04c3 ready.

you are using non-interactive mdoel quantaxis

Traceback (most recent call last):

File "/opt/conda/bin/quantaxis_webserver", line 5, in <module>

from QAWebServer.QA_Web import main

File "/opt/conda/lib/python3.8/site-packages/QAWebServer/__init__.py", line 29, in <module>

from QAWebServer.QA_Web import main

File "/opt/conda/lib/python3.8/site-packages/QAWebServer/QA_Web.py", line 47, in <module>

from QAWebServer.select_codehandler import SelectCodehandler

File "/opt/conda/lib/python3.8/site-packages/QAWebServer/select_codehandler.py", line 5, in <module>

class SelectCodehandler(QABaseHandler):

File "/opt/conda/lib/python3.8/site-packages/QAWebServer/select_codehandler.py", line 18, in SelectCodehandler

stocklist= QA.QA_fetch_stock_list_adv()

File "/opt/conda/lib/python3.8/site-packages/QUANTAXIS/QAFetch/QAQuery_Advance.py", line 492, in QA_fetch_stock_list_adv

stock_list_items = QA_fetch_stock_list(collections)

File "/opt/conda/lib/python3.8/site-packages/QUANTAXIS/QAFetch/QAQuery.py", line 401, in QA_fetch_stock_list

return pd.DataFrame([item for item in collections.find()]).drop(

File "/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py", line 4167, in drop

return super().drop(

File "/opt/conda/lib/python3.8/site-packages/pandas/core/generic.py", line 3889, in drop

obj = obj._drop_axis(labels, axis, level=level, errors=errors)

File "/opt/conda/lib/python3.8/site-packages/pandas/core/generic.py", line 3923, in _drop_axis

new_axis = axis.drop(labels, errors=errors)

File "/opt/conda/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 5287, in drop

raise KeyError(f"{labels[mask]} not found in axis")

KeyError: "['_id'] not found in axis"

## 感谢您的反馈 如有意见和建议,请在此说明:
盼复，非常感谢

## 您的联系方式(QQ/EMAIL)

THANKS
by yutiansut
2017.12

**Comment by yutiansut** [comment]
这个是因为网络不好导致数据没获取到

**Comment by chino1918** [comment]
谢谢天神，应该是上午网络或tdx接口抽风了，现在可以了。多谢多谢
