### ISSUE TITLE
realtime collector 订阅成功 但是exchange里面没数据进来

### ISSUE THREAD

**Issue by kelvin1757** [yutiansut/QUANTAXIS#1657]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?
1.10.2

## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
win10 64 16

## 您的系统环境是什么?
```
- monodb
- python3.8
- docker(有)
```

## 您需要反馈的问题
使用docker-compose3.yaml启动的reailtimecollector 

![image](https://user-images.githubusercontent.com/10300729/107460848-d900b980-6b93-11eb-926b-dbc7dc4b8cb4.png)
已经订阅成功
![image](https://user-images.githubusercontent.com/10300729/107460804-bf5f7200-6b93-11eb-9bd1-f655ebfe0120.png)
exchange中没数据进来 docker中也没报错 
![image](https://user-images.githubusercontent.com/10300729/107460928-fc2b6900-6b93-11eb-8bb6-44629800a10a.png)
用qaps_sub查看也是没数据

docker logs进realtimecollector 报一下错误

wait_for_it.sh: waiting 15 seconds for qaeventmq:5672
wait_for_it.sh: timeout occurred after waiting 15 seconds for qaeventmq:5672
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/QUANTAXIS/QAUtil/QASetting.py", line 99, in get_config
    return config.get(section, option)
  File "/usr/local/lib/python3.7/configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "/usr/local/lib/python3.7/configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'LOG'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/QARC_Stock", line 11, in <module>
    load_entry_point('qarealtime-collector', 'console_scripts', 'QARC_Stock')()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/root/QUANTAXIS_RealtimeCollector/QARealtimeCollector/__init__.py", line 7, in <module>
    from QARealtimeCollector.collectors import (QARTC_CtpBeeCollector,
  File "/root/QUANTAXIS_RealtimeCollector/QARealtimeCollector/collectors/__init__.py", line 1, in <module>
    from QARealtimeCollector.collectors.ctpbeecollector import QARTC_CtpBeeCollector
  File "/root/QUANTAXIS_RealtimeCollector/QARealtimeCollector/collectors/ctpbeecollector.py", line 5, in <module>
    from QUANTAXIS.QAUtil.QALogs import QA_util_log_info
  File "/usr/local/lib/python3.7/site-packages/QUANTAXIS/__init__.py", line 42, in <module>
    import QUANTAXIS.QACmd
  File "/usr/local/lib/python3.7/site-packages/QUANTAXIS/QACmd/__init__.py", line 35, in <module>
    from QUANTAXIS.QACmd.runner import run_backtest, run
  File "/usr/local/lib/python3.7/site-packages/QUANTAXIS/QACmd/runner.py", line 5, in <module>
    from QUANTAXIS.QAUtil.QALogs import QA_util_log_info
  File "/usr/local/lib/python3.7/site-packages/QUANTAXIS/QAUtil/__init__.py", line 41, in <module>
    from QUANTAXIS.QAUtil.QADate import (QA_util_calc_time, QA_util_date_int2str,
  File "/usr/local/lib/python3.7/site-packages/QUANTAXIS/QAUtil/QADate.py", line 31, in <module>
    from QUANTAXIS.QAUtil.QALogs import QA_util_log_info
  File "/usr/local/lib/python3.7/site-packages/QUANTAXIS/QAUtil/QALogs.py", line 47, in <module>
    'LOG', 'path', log_path), exist_ok=True)
  File "/usr/local/lib/python3.7/site-packages/QUANTAXIS/QAUtil/QASetting.py", line 101, in get_config
    res = self.client.quantaxis.usersetting.find_one({'section': section})
  File "/usr/local/lib/python3.7/site-packages/pymongo/collection.py", line 1273, in find_one
    for result in cursor.limit(-1):
  File "/usr/local/lib/python3.7/site-packages/pymongo/cursor.py", line 1156, in next
    if len(self.__data) or self._refresh():
  File "/usr/local/lib/python3.7/site-packages/pymongo/cursor.py", line 1050, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1806, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1759, in __start_session
    server_session = self._get_server_session()
  File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1792, in _get_server_session
    return self._topology.get_server_session()
  File "/usr/local/lib/python3.7/site-packages/pymongo/topology.py", line 485, in get_server_session
    None)
  File "/usr/local/lib/python3.7/site-packages/pymongo/topology.py", line 209, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: 192.168.0.101:27017: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/QUANTAXIS/QAUtil/QASetting.py", line 99, in get_config
    return config.get(section, option)
  File "/usr/local/lib/python3.7/configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "/usr/local/lib/python3.7/configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'LOG'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/QARC_WEBSERVER", line 11, in <module>
    load_entry_point('qarealtime-collector', 'console_scripts', 'QARC_WEBSERVER')()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/root/QUANTAXIS_RealtimeCollector/QARealtimeCollector/__init__.py", line 7, in <module>
    from QARealtimeCollector.collectors import (QARTC_CtpBeeCollector,
  File "/root/QUANTAXIS_RealtimeCollector/QARealtimeCollector/collectors/__init__.py", line 1, in <module>
    from QARealtimeCollector.collectors.ctpbeecollector import QARTC_CtpBeeCollector
  File "/root/QUANTAXIS_RealtimeCollector/QARealtimeCollector/collectors/ctpbeecollector.py", line 5, in <module>
    from QUANTAXIS.QAUtil.QALogs import QA_util_log_info
  File "/usr/local/lib/python3.7/site-packages/QUANTAXIS/__init__.py", line 42, in <module>
    import QUANTAXIS.QACmd
  File "/usr/local/lib/python3.7/site-packages/QUANTAXIS/QACmd/__init__.py", line 35, in <module>
    from QUANTAXIS.QACmd.runner import run_backtest, run
  File "/usr/local/lib/python3.7/site-packages/QUANTAXIS/QACmd/runner.py", line 5, in <module>
    from QUANTAXIS.QAUtil.QALogs import QA_util_log_info
  File "/usr/local/lib/python3.7/site-packages/QUANTAXIS/QAUtil/__init__.py", line 41, in <module>
    from QUANTAXIS.QAUtil.QADate import (QA_util_calc_time, QA_util_date_int2str,
  File "/usr/local/lib/python3.7/site-packages/QUANTAXIS/QAUtil/QADate.py", line 31, in <module>
    from QUANTAXIS.QAUtil.QALogs import QA_util_log_info
  File "/usr/local/lib/python3.7/site-packages/QUANTAXIS/QAUtil/QALogs.py", line 47, in <module>
    'LOG', 'path', log_path), exist_ok=True)
  File "/usr/local/lib/python3.7/site-packages/QUANTAXIS/QAUtil/QASetting.py", line 101, in get_config
    res = self.client.quantaxis.usersetting.find_one({'section': section})
  File "/usr/local/lib/python3.7/site-packages/pymongo/collection.py", line 1273, in find_one
    for result in cursor.limit(-1):
  File "/usr/local/lib/python3.7/site-packages/pymongo/cursor.py", line 1156, in next
    if len(self.__data) or self._refresh():
  File "/usr/local/lib/python3.7/site-packages/pymongo/cursor.py", line 1050, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1806, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1759, in __start_session
    server_session = self._get_server_session()
  File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1792, in _get_server_session
    return self._topology.get_server_session()
  File "/usr/local/lib/python3.7/site-packages/pymongo/topology.py", line 485, in get_server_session
    None)
  File "/usr/local/lib/python3.7/site-packages/pymongo/topology.py", line 209, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: 192.168.0.101:27017: [Errno 111] Connection refused
wait_for_it.sh: waiting 15 seconds for qaeventmq:5672
wait_for_it.sh: timeout occurred after waiting 15 seconds for qaeventmq:5672
PLEASE install TALIB to call these methods
PLEASE install TALIB to call these methods
no display found. Using non-interactive Agg backend
if you use ssh, you can use ssh with -X parmas to avoid this issue
wait_for_it.sh: waiting 15 seconds for qaeventmq:5672
wait_for_it.sh: qaeventmq:5672 is available after 14 seconds
PLEASE install TALIB to call these methods
PLEASE install TALIB to call these methods
no display found. Using non-interactive Agg backend
if you use ssh, you can use ssh with -X parmas to avoid this issue
QUANTAXIS>> 400 POST /?action=get_current_handler (10.0.2.2): Missing argument market_type
QUANTAXIS>> 400 POST /?action=get_current_handler (10.0.2.2) 36.43ms
wait_for_it.sh: waiting 15 seconds for qaeventmq:5672
wait_for_it.sh: timeout occurred after waiting 15 seconds for qaeventmq:5672
PLEASE install TALIB to call these methods
PLEASE install TALIB to call these methods
no display found. Using non-interactive Agg backend
if you use ssh, you can use ssh with -X parmas to avoid this issue
QUANTAXIS>> _AsyncBaseTransport._consume() failed, aborting connection: error=ConnectionResetError(104, 'Connection reset by peer'); sock=<socket.socket fd=34, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.19.0.8', 49676)>; Caller's stack:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 1037, in _on_socket_readable
    self._consume()
  File "/usr/local/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 786, in _consume
    data = self._sigint_safe_recv(self._sock, self._MAX_RECV_BYTES)
  File "/usr/local/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 74, in retry_sigint_wrap
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 840, in _sigint_safe_recv
    return sock.recv(max_bytes)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 1037, in _on_socket_readable
    self._consume()
  File "/usr/local/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 786, in _consume
    data = self._sigint_safe_recv(self._sock, self._MAX_RECV_BYTES)
  File "/usr/local/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 74, in retry_sigint_wrap
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 840, in _sigint_safe_recv
    return sock.recv(max_bytes)
ConnectionResetError: [Errno 104] Connection reset by peer
QUANTAXIS>> connection_lost: StreamLostError: ("Stream connection lost: ConnectionResetError(104, 'Connection reset by peer')",)
QUANTAXIS>> _AsyncBaseTransport._consume() failed, aborting connection: error=ConnectionResetError(104, 'Connection reset by peer'); sock=<socket.socket fd=46, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.19.0.8', 49688)>; Caller's stack:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 1037, in _on_socket_readable
    self._consume()
  File "/usr/local/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 786, in _consume
    data = self._sigint_safe_recv(self._sock, self._MAX_RECV_BYTES)
  File "/usr/local/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 74, in retry_sigint_wrap
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 840, in _sigint_safe_recv
    return sock.recv(max_bytes)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 1037, in _on_socket_readable
    self._consume()
  File "/usr/local/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 786, in _consume
    data = self._sigint_safe_recv(self._sock, self._MAX_RECV_BYTES)
  File "/usr/local/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 74, in retry_sigint_wrap
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 840, in _sigint_safe_recv
    return sock.recv(max_bytes)
ConnectionResetError: [Errno 104] Connection reset by peer
QUANTAXIS>> connection_lost: StreamLostError: ("Stream connection lost: ConnectionResetError(104, 'Connection reset by peer')",)
QUANTAXIS>> _AsyncBaseTransport._consume() failed, aborting connection: error=ConnectionResetError(104, 'Connection reset by peer'); sock=<socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.19.0.8', 49590)>; Caller's stack:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 1037, in _on_socket_readable
    self._consume()
  File "/usr/local/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 786, in _consume
    data = self._sigint_safe_recv(self._sock, self._MAX_RECV_BYTES)
  File "/usr/local/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 74, in retry_sigint_wrap
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 840, in _sigint_safe_recv
    return sock.recv(max_bytes)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 1037, in _on_socket_readable
    self._consume()
  File "/usr/local/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 786, in _consume
    data = self._sigint_safe_recv(self._sock, self._MAX_RECV_BYTES)
  File "/usr/local/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 74, in retry_sigint_wrap
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pika/adapters/utils/io_services_utils.py", line 840, in _sigint_safe_recv
    return sock.recv(max_bytes)
ConnectionResetError: [Errno 104] Connection reset by peer
QUANTAXIS>> Unexpected connection close detected: StreamLostError: ("Stream connection lost: ConnectionResetError(104, 'Connection reset by peer')",)
QUANTAXIS>> Unexpected connection close detected: StreamLostError: ("Stream connection lost: ConnectionResetError(104, 'Connection reset by peer')",)
QUANTAXIS>> connection_lost: StreamLostError: ("Stream connection lost: ConnectionResetError(104, 'Connection reset by peer')",)
wait_for_it.sh: waiting 15 seconds for qaeventmq:5672
wait_for_it.sh: timeout occurred after waiting 15 seconds for qaeventmq:5672
PLEASE install TALIB to call these methods
PLEASE install TALIB to call these methods
no display found. Using non-interactive Agg backend
if you use ssh, you can use ssh with -X parmas to avoid this issue

## 感谢您的反馈 如有意见和建议,请在此说明:
这里提示mongo和mq都不能连接 不过我这里mongo和mq都是能使用的 是不是docker的问题？

## 您的联系方式(QQ/EMAIL)

1011033727

THANKS
by kelvin

**Comment by kelvin1757** [comment]
解决了 使用非docker的mongo 会有这个bug 使用docker的mongo问题解决
window 本地部署collector qarc_webserver启动的时候tornado会报一个nonimplmenterror
找到这个项目使用的python环境的lib\site-packages，做下面的修改，在path-to-python\lib\site-packages\tornado\platform\asyncio.py开头添加代码：
import sys
if sys.platform == 'win32':
  asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
