### ISSUE TITLE
pip装完qatrader后创建账户报错

### ISSUE THREAD

**Issue by jamesxu326** [yutiansut/QUANTAXIS#1666]
# 问题反馈

Exception
当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?
最新版本
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
![image](https://user-images.githubusercontent.com/758645/108387900-08c15880-7249-11eb-83d6-fc48c784c64d.png)

## 您的系统环境是什么?
```
- monodb
- 有
- python3.7/3.8
- 3.8
- docker(有无)
- 有
```

## 您需要反馈的问题
我是mac系统
在本地环境（以及jupyter的cmd环境）中执行pip3 install qatrader安装成功

执行命令如下：

qatrader --acc 10010 --pwd 10010 --broker QUANTAXIS

输出如下：
jqdatasdk not installed
send_ping
QUANTAXIS>> updateAccount
<class 'Exception'>
Exception in thread QATRADER_10010:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/QATRADER/trader.py", line 129, in ping
    self.ws.sock.ping('{}-{}'.format('ping', self.account_cookie))
  File "/usr/local/lib/python3.8/site-packages/websocket/_core.py", line 295, in ping
    self.send(payload, ABNF.OPCODE_PING)
  File "/usr/local/lib/python3.8/site-packages/websocket/_core.py", line 253, in send
    return self.send_frame(frame)
  File "/usr/local/lib/python3.8/site-packages/websocket/_core.py", line 279, in send_frame
    l = self._send(data)
  File "/usr/local/lib/python3.8/site-packages/websocket/_core.py", line 449, in _send
    return send(self.sock, data)
  File "/usr/local/lib/python3.8/site-packages/websocket/_socket.py", line 135, in send
    raise WebSocketConnectionClosedException("socket is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: socket is already closed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.7_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/site-packages/QATRADER/trader.py", line 181, in run
    self.ping()
  File "/usr/local/lib/python3.8/site-packages/QATRADER/trader.py", line 137, in ping
    raise Exception

## 您的联系方式(QQ/EMAIL)
lingzhixu326@163.coom

THANKS
by yutiansut
2017.12

**Comment by yutiansut** [comment]
开盘时间再试一下 @jamesxu326

**Comment by jamesxu326** [comment]
刚刚试了一下，还是报同样的错误
