### ISSUE TITLE
无法下载高级财务数据

### ISSUE THREAD

**Issue by balsid** [yutiansut/QUANTAXIS#1694]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?
1.10.9
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
Windows 10 Home, x64, 8G RAM

## 您的系统环境是什么?
```
- monodb 4.4
- python 3.8.5
- docker(有)
```

## 您需要反馈的问题

我安装docker后可以下载stock_list，但当下载高级财务数据时出错，出错信息如下，不知是否缺少什么？多谢！

QUANTAXIS> save financialfiles
Traceback (most recent call last):
  File "/opt/conda/bin/quantaxis", line 8, in <module>
    sys.exit(QA_cmd())
  File "/opt/conda/lib/python3.8/site-packages/QUANTAXIS/QACmd/__init__.py", line 686, in QA_cmd
    cli.cmdloop()
  File "/opt/conda/lib/python3.8/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/opt/conda/lib/python3.8/cmd.py", line 217, in onecmd
    return func(arg)
  File "/opt/conda/lib/python3.8/site-packages/QUANTAXIS/QACmd/__init__.py", line 552, in do_save
    QA_SU_save_financialfiles()
  File "/opt/conda/lib/python3.8/site-packages/QUANTAXIS/QASU/main.py", line 619, in QA_SU_save_financialfiles
    return save_financialfiles.QA_SU_save_financial_files()
  File "/opt/conda/lib/python3.8/site-packages/QUANTAXIS/QASU/save_financialfiles.py", line 45, in QA_SU_save_financial_files
    download_financialzip()
  File "/opt/conda/lib/python3.8/site-packages/QUANTAXIS/QAFetch/QAfinancial.py", line 94, in download_financialzip
    result = get_filename()
  File "/opt/conda/lib/python3.8/site-packages/QUANTAXIS/QAFetch/QAfinancial.py", line 83, in get_filename
    return [(l[0], l[1]) for l in [line.strip().split(",") for line in requests.get(FINANCIAL_URL).text.strip().split('\n')]]
  File "/opt/conda/lib/python3.8/site-packages/QUANTAXIS/QAFetch/QAfinancial.py", line 83, in <listcomp>
    return [(l[0], l[1]) for l in [line.strip().split(",") for line in requests.get(FINANCIAL_URL).text.strip().split('\n')]]
IndexError: list index out of range

## 您的联系方式(QQ/EMAIL)
dislab@gmail.com

THANKS
by yutiansut
2017.12

**Comment by yutiansut** [comment]
可以重新试一下 似乎是你的网络问题

**Comment by balsid** [comment]
似乎不是网络问题，因为下载其他的如stock_list, index_day等都没有问题，不过我是从国外连的。我是从docker里的qacommunity-rust打开一个CLI，然后启动quantaxis，然后运行"save finanicalfiles"。下载 financailfiles需要什么额外的权限吗？新手一个。谢谢！

**Comment by balsid** [comment]
看了一下，发生的错误是因为无法访问FINANCIAL_URL：'http://data.yutiansut.com/content.txt‘，不知这个文件还在吗，还是不能从国外访问？谢谢！

**Comment by yutiansut** [comment]
你这是因为长时间没有更新qa的原因 这个地址早就弃用了  

pip install quantaxis -U

**Comment by balsid** [comment]
多谢! 请问一般应该如何更新qa，是每隔几天手工run一次“pip install quantaxis -U”, 然后在docker里重启qa吗？
