### ISSUE TITLE
save future和save future_day无法下载数据

### ISSUE THREAD

**Issue by gongchuan** [yutiansut/QUANTAXIS#1709]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?
QUANTAXIS> version
QUANTAXIS>> 1.10.12
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)

centos 8 64 8G
## 您的系统环境是什么?
```
- monodb
- python3.7/3.8
- docker(有无\)
```

## 您需要反馈的问题
save future无法保存数据

QUANTAXIS> save future
QUANTAXIS>> Selecting the Best Server IP of TDX
USING DEFAULT STOCK IP
USING DEFAULT FUTURE IP
QUANTAXIS>> === The BEST SERVER ===
 stock_ip 119.147.164.60 future_ip 47.107.75.159
Traceback (most recent call last):
  File "/opt/conda/bin/quantaxis", line 8, in <module>
    sys.exit(QA_cmd())
  File "/opt/conda/lib/python3.8/site-packages/QUANTAXIS/QACmd/__init__.py", line 735, in QA_cmd
    cli.cmdloop()
  File "/opt/conda/lib/python3.8/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/opt/conda/lib/python3.8/cmd.py", line 217, in onecmd
    return func(arg)
  File "/opt/conda/lib/python3.8/site-packages/QUANTAXIS/QACmd/__init__.py", line 603, in do_save
    QA_SU_save_future_day("tdx")
  File "/opt/conda/lib/python3.8/site-packages/QUANTAXIS/QASU/main.py", line 152, in QA_SU_save_future_day
    engine.QA_SU_save_future_day(client=client)
  File "/opt/conda/lib/python3.8/site-packages/QUANTAXIS/QASU/save_tdx.py", line 5902, in QA_SU_save_future_day
    item for item in QA_fetch_get_future_list().code.unique().tolist()
  File "/opt/conda/lib/python3.8/site-packages/QUANTAXIS/QAFetch/QATdx.py", line 1452, in QA_fetch_get_future_list
    extension_market_list = QA_fetch_get_extensionmarket_list(
  File "/opt/conda/lib/python3.8/site-packages/QUANTAXIS/QAFetch/QATdx.py", line 1429, in QA_fetch_get_extensionmarket_list
    return pd.concat([apix.to_df(
  File "/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py", line 4555, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['code'] are in the columns"
(base) root@7b34cebb5571:~# quantaxis
提示：当前环境 pandas 版本高于 0.25，get_price 与 get_fundamentals_continuously 接口 panel 参数将固定为 False
注意：0.25 以上版本 pandas 不支持 panel，如使用该数据结构和相关函数请注意修改
you are using non-interactive mdoel quantaxis

QUANTAXIS> save future_day
QUANTAXIS>> Selecting the Best Server IP of TDX
USING DEFAULT STOCK IP
USING DEFAULT FUTURE IP
QUANTAXIS>> === The BEST SERVER ===
 stock_ip 119.147.164.60 future_ip 47.107.75.159
❌命令格式不正确！
Usage: 

## 您的联系方式(QQ/EMAIL)
642019259@qq.com

THANKS
by yutiansut
2017.12

**Comment by quantunm** [comment]
我也有同样的问题。。。

**Comment by quantunm** [comment]
原来这问题不是只有我一个人有。。。

**Comment by quantunm** [comment]
回退到旧版本也不行，单步进去看这两个命令返回的都是股票数据，应该是tdx那边改接口了。。。

**Comment by quantunm** [comment]
应该不是quantaxis的问题，是tdx那边的。这会儿已经OK了。

**Comment by James1010422846** [comment]
怎么ok的。我这里还是报错

**Comment by quantunm** [comment]
已经又不行很长一段时间了。单步调试看可能是通达信那边改协议了。pytdx里面ex_setup_commands.py下ExSetupCmd1.setup() 发送出去后没法收到返回报文。换了好几个ip和port都是一样的结果。

**Comment by zqq0ew0** [comment]
我现在 也是这个问题 怎么解决呢？

**Comment by LJNL** [comment]
通达信服务端升级协议后期货数据的包头变了，需修改pytdx。在群里有新的pytdx.whl 安装到docker中即可。

**Comment by linshenqi** [comment]
在容器内安装好最新的pytdx.whl ，记得通过docker restart 重启容器

**Comment by wan9c9** [comment]
Hi, 我也遇到这个问题，请问方便个我发个pytdx.whl 吗？多谢啦 （wan9c9@gmail.com)
