### ISSUE TITLE
mac docker一键部署报错，qaweb模块

### ISSUE THREAD

**Issue by houyce** [yutiansut/QUANTAXIS#1711]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您的系统环境是什么?
```
- mac os
- monodb
- python3.8
- docker（有）
```

## 您需要反馈的问题
Traceback (most recent call last):
Traceback (most recent call last):
  File "/opt/conda/bin/qifi_manager", line 5, in <module>
  File "/opt/conda/bin/quantaxis_webserver", line 5, in <module>
    from qifimanager.__init__ import run_server
  File "/opt/conda/lib/python3.8/site-packages/qifimanager/__init__.py", line 5, in <module>
    from qifimanager.qifiwebserver import QAQIFI_Handler, QAQIFIS_Handler
  File "/opt/conda/lib/python3.8/site-packages/qifimanager/qifiwebserver.py", line 2, in <module>
    from QAWebServer.QA_Web import main
  File "/opt/conda/lib/python3.8/site-packages/QAWebServer/__init__.py", line 29, in <module>
    from QAWebServer.basehandles import QABaseHandler
  File "/opt/conda/lib/python3.8/site-packages/QAWebServer/__init__.py", line 29, in <module>
    from QAWebServer.QA_Web import main
  File "/opt/conda/lib/python3.8/site-packages/QAWebServer/QA_Web.py", line 47, in <module>
Traceback (most recent call last):
      File "/opt/conda/bin/qavifiserver", line 5, in <module>
from QAWebServer.QA_Web import main
  File "/opt/conda/lib/python3.8/site-packages/QAWebServer/QA_Web.py", line 47, in <module>
        from QAWebServer.select_codehandler import SelectCodehandler
  File "/opt/conda/lib/python3.8/site-packages/QAWebServer/select_codehandler.py", line 5, in <module>
from qavifiserver.__init__ import run_server
  File "/opt/conda/lib/python3.8/site-packages/qavifiserver/__init__.py", line 5, in <module>
    class SelectCodehandler(QABaseHandler):
  File "/opt/conda/lib/python3.8/site-packages/QAWebServer/select_codehandler.py", line 18, in SelectCodehandler
        stocklist= QA.QA_fetch_stock_list_adv()
  File "/opt/conda/lib/python3.8/site-packages/QUANTAXIS/QAFetch/QAQuery_Advance.py", line 492, in QA_fetch_stock_list_adv
from qavifiserver.qahqchart import QAHqchartDailyHandler, QAHqchartKlineHandler
  File "/opt/conda/lib/python3.8/site-packages/qavifiserver/qahqchart.py", line 6, in <module>
        stock_list_items = QA_fetch_stock_list(collections)
  File "/opt/conda/lib/python3.8/site-packages/QUANTAXIS/QAFetch/QAQuery.py", line 401, in QA_fetch_stock_list
from QAWebServer.basehandles import QABaseHandler
      File "/opt/conda/lib/python3.8/site-packages/QAWebServer/__init__.py", line 29, in <module>
from QAWebServer.select_codehandler import SelectCodehandler
  File "/opt/conda/lib/python3.8/site-packages/QAWebServer/select_codehandler.py", line 5, in <module>
    class SelectCodehandler(QABaseHandler):
  File "/opt/conda/lib/python3.8/site-packages/QAWebServer/select_codehandler.py", line 18, in SelectCodehandler
    return pd.DataFrame([item for item in collections.find()]).drop(
  File "/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py", line 4167, in drop
        stocklist= QA.QA_fetch_stock_list_adv()
  File "/opt/conda/lib/python3.8/site-packages/QUANTAXIS/QAFetch/QAQuery_Advance.py", line 492, in QA_fetch_stock_list_adv
from QAWebServer.QA_Web import main
  File "/opt/conda/lib/python3.8/site-packages/QAWebServer/QA_Web.py", line 47, in <module>
    stock_list_items = QA_fetch_stock_list(collections)
  File "/opt/conda/lib/python3.8/site-packages/QUANTAXIS/QAFetch/QAQuery.py", line 401, in QA_fetch_stock_list
    from QAWebServer.select_codehandler import SelectCodehandler
      File "/opt/conda/lib/python3.8/site-packages/QAWebServer/select_codehandler.py", line 5, in <module>
return pd.DataFrame([item for item in collections.find()]).drop(
  File "/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py", line 4167, in drop
    return super().drop(
  File "/opt/conda/lib/python3.8/site-packages/pandas/core/generic.py", line 3889, in drop
    class SelectCodehandler(QABaseHandler):
  File "/opt/conda/lib/python3.8/site-packages/QAWebServer/select_codehandler.py", line 18, in SelectCodehandler
    stocklist= QA.QA_fetch_stock_list_adv()
  File "/opt/conda/lib/python3.8/site-packages/QUANTAXIS/QAFetch/QAQuery_Advance.py", line 492, in QA_fetch_stock_list_adv
    return super().drop(
  File "/opt/conda/lib/python3.8/site-packages/pandas/core/generic.py", line 3889, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/opt/conda/lib/python3.8/site-packages/pandas/core/generic.py", line 3923, in _drop_axis
    stock_list_items = QA_fetch_stock_list(collections)
  File "/opt/conda/lib/python3.8/site-packages/QUANTAXIS/QAFetch/QAQuery.py", line 401, in QA_fetch_stock_list
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/opt/conda/lib/python3.8/site-packages/pandas/core/generic.py", line 3923, in _drop_axis
    return pd.DataFrame([item for item in collections.find()]).drop(
    new_axis = axis.drop(labels, errors=errors)
  File "/opt/conda/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 5287, in drop
  File "/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py", line 4167, in drop
    new_axis = axis.drop(labels, errors=errors)
  File "/opt/conda/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 5287, in drop
    return super().drop(
  File "/opt/conda/lib/python3.8/site-packages/pandas/core/generic.py", line 3889, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
    KeyErrorraise KeyError(f"{labels[mask]} not found in axis"): 
"['_id'] not found in axis"KeyError: "['_id'] not found in axis"

    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/opt/conda/lib/python3.8/site-packages/pandas/core/generic.py", line 3923, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "/opt/conda/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 5287, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['_id'] not found in axis"
[2021-06-09 18:24:47,920: INFO/MainProcess] celery@5bb5b74030f3 ready.

## 感谢您的反馈 如有意见和建议,请在此说明:

docker一键部署

## 您的联系方式(QQ/EMAIL)
379767986

THANKS
by yutiansut
2021.06

**Comment by seasidemym** [comment]
同样的问题，mac m1, docker-compose up直接启动

**Comment by yutiansut** [comment]
save stock_list
