### ISSUE TITLE
QAStrategy依赖问题

### ISSUE THREAD

**Issue by wangyajieI** [yutiansut/QUANTAXIS#1781]
hi,云神：
    请教一个问题：是否`QAStrategy` 这个包已经不推荐使用了？或者已经有了替代的回测接口？
    我发现最新的QUANTAXIS移除了`QAARP`这个包，但是使用最新的`QAStrategy`做回测时，貌似还是会依赖`QAARP`这个包，比如`QIFIAccount\QAPosition.py` 第五行有`from QUANTAXIS.QAARP.market_preset import MARKET_PRESET`, 此时如果代码使用了QAPosition包，就会报错，例如如下代码
 ```python
from QAStrategy.qastockbase import QAStrategyStockBase
import QUANTAXIS as QA
import pandas as pd
```
即会报import 失败
```python
Traceback (most recent call last):
  File ".\retest_demo_01.py", line 2, in <module>
    from QAStrategy.qastockbase import QAStrategyStockBase
  File "code\quantaxis\qastrategy\QAStrategy\__init__.py", line 6, in <module>
    from QAStrategy.qactabase import QAStrategyCTABase
  File "code\quantaxis\qastrategy\QAStrategy\qactabase.py", line 21, in <module>
    from QIFIAccount import ORDER_DIRECTION, QIFI_Account
  File "python3\lib\site-packages\QIFIAccount\__init__.py", line 1, in <module>
    from QIFIAccount.QAQIFIAccount import QIFI_Account, ORDER_DIRECTION
  File "python3\lib\site-packages\QIFIAccount\QAQIFIAccount.py", line 8, in <module>
    from QIFIAccount.QAPosition import QA_Position
  File "python3\lib\site-packages\QIFIAccount\QAPosition.py", line 5, in <module>
    from QUANTAXIS.QAARP.market_preset import MARKET_PRESET
ModuleNotFoundError: No module named 'QUANTAXIS.QAARP'
```

**Comment by yutiansut** [comment]
可以用这个 https://github.com/QUANTAXIS/QUANTAXIS/tree/master/QUANTAXIS/QAStrategy

**Comment by kelvin1757** [comment]
2.0用不了 用quantaxis-1.10.19.post2这个版本可以

**Comment by qinjie545** [comment]
> 可以用这个 https://github.com/QUANTAXIS/QUANTAXIS/tree/master/QUANTAXIS/QAStrategy

65行还是有个依赖


```
 self.market_preset = QA.QAARP.MARKET_PRESET()
```
