### ISSUE TITLE
Failed to init data in quantaxis cli

### ISSUE THREAD

**Issue by frankwang314** [yutiansut/QUANTAXIS#1825]
hello  guys,

I'm a freshman to quantaxis, when I wanted to init data in quantaxis cli with command "save all", I got errors as following.
What I was wrong , any advise could be appreciated.

(venv) D:\py_workspace\QUANTAXIS>quantaxis
d:\py_workspace\quantaxis\QUANTAXIS\QAFetch\QAhuobi_realtime.py:667: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future versi
on. Specify a dtype explicitly to silence this warning.
  candleline=pd.Series(),
QUANTAXIS> save all
Traceback (most recent call last):
  File "D:\py_workspace\QUANTAXIS\venv\Scripts\quantaxis-script.py", line 33, in <module>
    sys.exit(load_entry_point('quantaxis', 'console_scripts', 'quantaxis')())
  File "d:\py_workspace\quantaxis\QUANTAXIS\QACmd\__init__.py", line 686, in QA_cmd
    cli.cmdloop()
  File "D:\Program Files\Python\Python38\lib\cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "D:\Program Files\Python\Python38\lib\cmd.py", line 217, in onecmd
    return func(arg)
  File "d:\py_workspace\quantaxis\QUANTAXIS\QACmd\__init__.py", line 340, in do_save
    if QA_Setting().client.quantaxis.user_list.find(
AttributeError: 'Cursor' object has no attribute 'count'

**Comment by yys123** [comment]
Sorry, I am not the author, I can not help you.

**Comment by yys123** [comment]
> Sorry, I am not the author, I can not help you.

**Comment by frankwang314** [comment]
Downgrade  python version to 3.6.8(win32), and upgrade pip to newest version, then the problem has been fixed.
