### ISSUE TITLE
qatrader运行异常

### ISSUE THREAD

**Issue by frankwang314** [yutiansut/QUANTAXIS#1830]
在启动qatrader的时候:
qatrader --acc 213586 --pwd xxxxxx --broker QUANTAXIS --wsuri ws://www.yutiansut.com:7988
报异常:
websocket._exceptions.WebSocketBadStatusException: Handshake status 403 Forbidden

大家有碰到类似的问题吗?

(venv) C:\Users\user>qatrader --acc 213586 --pwd xxxxxx --broker QUANTAXIS --wsuri ws://www.yutiansut.com:7988
d:\py_workspace\quantaxis\venv\lib\site-packages\QUANTAXIS\QAFetch\QAhuobi_realtime.py:667: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  candleline=pd.Series(),
Handshake status 403 Forbidden
QUANTAXIS>> TRADE LOG OUT! CONNECTION LOST
Traceback (most recent call last):
  File "d:\py_workspace\quantaxis\venv\lib\site-packages\websocket\_app.py", line 249, in run_forever
    self.sock.connect(
  File "d:\py_workspace\quantaxis\venv\lib\site-packages\websocket\_core.py", line 226, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "d:\py_workspace\quantaxis\venv\lib\site-packages\websocket\_handshake.py", line 80, in handshake
    status, resp = _get_resp_headers(sock)
  File "d:\py_workspace\quantaxis\venv\lib\site-packages\websocket\_handshake.py", line 165, in _get_resp_headers
    raise WebSocketBadStatusException("Handshake status %d %s", status, status_message, resp_headers)
websocket._exceptions.WebSocketBadStatusException: Handshake status 403 Forbidden
QUANTAXIS>> updateAccount
send_ping
QUANTAXIS>> updateAccount
<class 'Exception'>
Exception in thread QATRADER_213586:
Traceback (most recent call last):
  File "d:\py_workspace\quantaxis\venv\lib\site-packages\QATRADER\trader.py", line 124, in ping
    self.ws.sock.ping('{}-{}'.format('ping', self.account_cookie))
AttributeError: 'NoneType' object has no attribute 'ping'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "d:\py_workspace\quantaxis\venv\lib\site-packages\QATRADER\trader.py", line 176, in run
    self.ping()
  File "d:\py_workspace\quantaxis\venv\lib\site-packages\QATRADER\trader.py", line 132, in ping
    raise Exception
Exception

**Comment by yutiansut** [comment]
自己本地部署qatradeg就可以啦

**Comment by simonjhy** [comment]
这个qatradeg怎么在本地部署，有简单的文档吗
