### ISSUE TITLE
docker ubuntu下无法运行 backtest.py

### ISSUE THREAD

**Issue by duanrb** [yutiansut/QUANTAXIS#252]
我在docker的unbuntu下安装了quantaxis后无法运行 backtest.py，请问是什么原因？谢谢

=========================================
root@27add3d50ee6:~/saveall# python3.6 backtest.py
QUANTAXIS>> start QUANTAXIS
...............
QUANTAXIS>> success login! your username is:admin
/root/quantaxis/QUANTAXIS/QAData/data_fq.py:52: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  bfq_data['if_trade']=1
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexes/base.py", line 2442, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc (pandas/_libs/index.c:5280)
  File "pandas/_libs/index.pyx", line 154, in pandas._libs.index.IndexEngine.get_loc (pandas/_libs/index.c:5126)
  File "pandas/_libs/hashtable_class_helper.pxi", line 1210, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas/_libs
/hashtable.c:20523)
  File "pandas/_libs/hashtable_class_helper.pxi", line 1218, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas/_libs
/hashtable.c:20477)
KeyError: (Timestamp('2016-05-17 00:00:00'), '000001')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexes/base.py", line 3481, in get_slice_bound
    slc = self._get_loc_only_exact_matches(label)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexes/base.py", line 3450, in _get_loc_only_exact_matches
    return self.get_loc(key)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexes/base.py", line 2444, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc (pandas/_libs/index.c:5280)
  File "pandas/_libs/index.pyx", line 154, in pandas._libs.index.IndexEngine.get_loc (pandas/_libs/index.c:5126)
  File "pandas/_libs/hashtable_class_helper.pxi", line 1210, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas/_libs/hashtable.c:20523)
  File "pandas/_libs/hashtable_class_helper.pxi", line 1218, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas/_libs/hashtable.c:20477)
KeyError: (Timestamp('2016-05-17 00:00:00'), '000001')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "backtest.py", line 97, in <module>
    @QB.backtest_init
  File "/root/quantaxis/QUANTAXIS/QABacktest/QABacktest.py", line 797, in backtest_init
    return __init_backtest(_cls)
  File "/root/quantaxis/QUANTAXIS/QABacktest/QABacktest.py", line 796, in __init_backtest
    _cls.__QA_backtest_prepare(_cls)
  File "/root/quantaxis/QUANTAXIS/QABacktest/QABacktest.py", line 212, in __QA_backtest_prepare
    self.strategy_gap + 1)], self.trade_list[self.end_real_id]).to_qfq()
  File "/root/quantaxis/QUANTAXIS/QAData/QADataStruct.py", line 607, in to_qfq
    lambda x: QA_data_stock_to_fq(self.data[self.data['code'] == x]), self.code))))
  File "/root/quantaxis/QUANTAXIS/QAData/QADataStruct.py", line 607, in <lambda>
    lambda x: QA_data_stock_to_fq(self.data[self.data['code'] == x]), self.code))))
  File "/root/quantaxis/QUANTAXIS/QAData/data_fq.py", line 112, in QA_data_stock_to_fq
    return QA_data_make_qfq(__data, __QA_fetch_stock_xdxr(__data['code'][0]))
  File "/root/quantaxis/QUANTAXIS/QAData/data_fq.py", line 53, in QA_data_make_qfq
    data = pd.concat([bfq_data, info[['category']][bfq_data.index[0]:bfq_data.index[-1]]], axis=1)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py", line 1952, in __getitem__
    indexer = convert_to_index_sliceable(self, key)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py", line 1896, in convert_to_index_sliceable
    return idx._convert_slice_indexer(key, kind='getitem')
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexes/base.py", line 1407, in _convert_slice_indexer
    indexer = self.slice_indexer(start, stop, step, kind=kind)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexes/base.py", line 3350, in slice_indexer
    kind=kind)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexes/base.py", line 3538, in slice_locs
    start_slice = self.get_slice_bound(start, 'left', kind)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexes/base.py", line 3484, in get_slice_bound
    return self._searchsorted_monotonic(label, side)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexes/base.py", line 3434, in _searchsorted_monotonic
    return self.searchsorted(label, side=side)
  File "/usr/local/lib/python3.6/dist-packages/pandas/util/_decorators.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/base.py", line 1167, in searchsorted
    return self.values.searchsorted(value, side=side, sorter=sorter)
  File "pandas/_libs/tslib.pyx", line 1080, in pandas._libs.tslib._Timestamp.__richcmp__ (pandas/_libs/tslib.c:20281)
TypeError: Cannot compare type 'Timestamp' with type 'str'

**Comment by yutiansut** [comment]
似乎是没有取到数据  你有存数据吗

**Comment by duanrb** [comment]
原来要等数据全部加载完成，数据加载完以后可以了，多谢解答 @yutiansut

**Comment by yutiansut** [comment]
我大致推测 你看你最后 的问题是timestamp和str的比较 也就是按timestamp取数据的时候 index里面实际上是str 那应该是没有取到数据返回的那个none.. 是个str

**Comment by yutiansut** [comment]
你是用docker的吗 能写一个docker的安装配置教程吗  我这块完全不大懂  @duanrb   如果能写的话 可以有现金奖励的哦~

**Comment by duanrb** [comment]
哈哈，可以啊，很乐意能做些贡献，强烈推荐使用docker，大大方便了开发和部署

**Comment by duanrb** [comment]
请加下我微信吧rubing001

**Comment by yutiansut** [comment]
@duanrb 加你了
