### ISSUE TITLE
pip 安装的时候，发生UnicodeDecodeError

### ISSUE THREAD

**Issue by mathlemon** [yutiansut/QUANTAXIS#418]
下面是错误的堆栈，不知道为什么安装的时候报错了。

PS D:\code\quantaxis> python -m pip install -e . -i https://pypi.doubanio.com/simple
Obtaining file:///D:/code/quantaxis
Exception:
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 62: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "D:\Anaconda3\lib\site-packages\pip\commands\install.py", line 335, in run
    wb.build(autobuilding=True)
  File "D:\Anaconda3\lib\site-packages\pip\wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "D:\Anaconda3\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "D:\Anaconda3\lib\site-packages\pip\req\req_set.py", line 518, in _prepare_file
    abstract_dist.prep_for_dist()
  File "D:\Anaconda3\lib\site-packages\pip\req\req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "D:\Anaconda3\lib\site-packages\pip\req\req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "D:\Anaconda3\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "D:\Anaconda3\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 62: invalid start byte

**Comment by yutiansut** [comment]
已解决  解决 办法是 先```python setup.py install ```一次 原因暂时不清楚

**Comment by kingvern** [comment]
查了下是编码问题，pip\compat\_init_.py 中是return s.decode('utf_8') 但是Windows的默认编码是gbk，实测一个可行的解决办法为在_init_.py 中查找return s.decode('utf_8') 改为return s.decode('gbk')，再执行

**Comment by yutiansut** [comment]
@kingvern  这个是pip的代码欸 你是直接改动的pip吗
