### ISSUE TITLE
执行到python -m pip install -e . -i https://pypi.doubanio.com/simple 时报错No module named 'pytdx'

### ISSUE THREAD

**Issue by kingvern** [yutiansut/QUANTAXIS#424]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?

```
最新版

```
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
```
Windows 10 64位 内存16G

```

## 您的系统环境是什么?
```
- monodb
- nodejs(V9以下版本)
- python3.6
- docker(无)
```
## 您需要反馈的问题
```
执行到python -m pip install -e . -i https://pypi.doubanio.com/simple 报错

Obtaining file:///C:/quantaxis
    Complete output from command python setup.py egg_info:
    QUANTAXIS>> start QUANTAXIS
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\quantaxis\setup.py", line 29, in <module>
        import QUANTAXIS
      File "C:\quantaxis\QUANTAXIS\__init__.py", line 57, in <module>
        from QUANTAXIS.QAFetch.Fetcher import QA_quotation  # 统一的获取接口
      File "C:\quantaxis\QUANTAXIS\QAFetch\__init__.py", line 36, in <module>
        from QUANTAXIS.QAFetch import QATdx as QATdx
      File "C:\quantaxis\QUANTAXIS\QAFetch\QATdx.py", line 28, in <module>
        from pytdx.exhq import TdxExHq_API
    ModuleNotFoundError: No module named 'pytdx'

```
## 感谢您的反馈 如有意见和建议,请在此说明:
```
目测是目录结构的问题？

```
## 您的联系方式(QQ/EMAIL)
```

```

THANKS
by yutiansut
2017.12

**Comment by yutiansut** [comment]
@kingvern 
```python

pip install tushare
pip install pytdx
```
