### ISSUE TITLE
手动安装QUANTAXIS报错

### ISSUE THREAD

**Issue by mzhe24** [yutiansut/QUANTAXIS#65]
# 问题反馈

当您安装/使用QUANTAXIS的时候如果遇到任何问题, 您可以在这里提出,我们会在24小时内给您答复

## 您使用的QUANTAXIS版本号是什么?

```
1.1.10.dev4


```
## 您的系统信息(包括系统版本,系统架构(32/64),内存大小等等)
```


vmware虚机 
Ubuntu 16.04 64位 4C 16G


```

## 您的系统环境是什么?
```
- monodb
- nodejs(V9以下版本)
- python3.5/3.6
- docker(有无)
```
## 您需要反馈的问题
```
先用ubuntu.sh安装，发现没有QUANATXIS_WebKit，就按照手动顺序检查并手动安装QUANTAXIS
安装QUANTAXIS时pip install -e . 报错无法安装
Exception:
Traceback (most recent call last):
  File "/home/ubstock01/anaconda3/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/ubstock01/anaconda3/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/ubstock01/anaconda3/lib/python3.6/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/ubstock01/anaconda3/lib/python3.6/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/ubstock01/anaconda3/lib/python3.6/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/home/ubstock01/anaconda3/lib/python3.6/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/home/ubstock01/anaconda3/lib/python3.6/site-packages/pip/wheel.py", line 329, in clobber
    os.utime(destfile, (st.st_atime, st.st_mtime))
PermissionError: [Errno 1] 不允许的操作


```
## 感谢您的反馈 如有意见和建议,请在此说明:
```



```
## 您的联系方式(QQ/EMAIL)
```
23811280/mzhe24@163.com
```

THANKS
by yutiansut
2017.12

**Comment by yutiansut** [comment]
没有权限 @mzhe24  sudo ......
