### ISSUE TITLE
安装完成后save all就把我卡住了

### ISSUE THREAD

**Issue by zhangshoug** [yutiansut/QUANTAXIS#736]
QUANTAXIS> save all
Traceback (most recent call last):
  File "/home/zhangshoug/anaconda3/bin/quantaxis", line 11, in <module>
    load_entry_point('quantaxis', 'console_scripts', 'quantaxis')()
  File "/home/zhangshoug/quantaxis/QUANTAXIS/QACmd/__init__.py", line 359, in QA_cmd
    cli.cmdloop()
  File "/home/zhangshoug/anaconda3/lib/python3.6/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/home/zhangshoug/anaconda3/lib/python3.6/cmd.py", line 217, in onecmd
    return func(arg)
  File "/home/zhangshoug/quantaxis/QUANTAXIS/QACmd/__init__.py", line 221, in do_save
    QA_SU_save_stock_day('tdx')
  File "/home/zhangshoug/quantaxis/QUANTAXIS/QASU/main.py", line 87, in QA_SU_save_stock_day
    engine.QA_SU_save_stock_day(client=client,ui_log=  ui_log, ui_progress = ui_progress, ui_progress_int_value = ui_progress_int_value)
TypeError: QA_SU_save_stock_day() got an unexpected keyword argument 'ui_progress_int_value'

**Comment by yutiansut** [comment]
抱歉 之前增加界面的时候 改动不完善 ~  现在已经修复了  版本号 1.0.69.dev1 @zhangshoug
