### ISSUE TITLE
Linux安装文档的步骤增加lxml安装

### ISSUE THREAD

**Issue by rainx** [yutiansut/QUANTAXIS#80]
在一个新的环境安装QUANTAXIS的时候，由于 QUANTAXIS 依赖了tushare，而tushare在pip安装之前需要提前安装lxml包，所以可能导致如下的报错，建议在文档的安装步骤上提示一下..  

```
rainx@ubuntu170:~/dev/QUANTAXIS$ sudo pip3.6 install -e .
The directory '/home/rainx/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/rainx/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Obtaining file:///home/rainx/dev/QUANTAXIS
Collecting pandas>=0.20 (from quantaxis==0.3.9b2.dev53)
  Downloading http://pypi.doubanio.com/packages/fe/6f/5733658857dffb998afa2120027171c263384ada0487a969e5ecd5bf9ac9/pandas-0.20.3-cp36-cp36m-manylinux1_x86_64.whl (24.5MB)
    100% |████████████████████████████████| 24.5MB 6.3MB/s
Collecting numpy>=1.12.0 (from quantaxis==0.3.9b2.dev53)
  Downloading http://pypi.doubanio.com/packages/59/e2/57c1a6af4ff0ac095dd68b12bf07771813dbf401faf1b97f5fc0cb963647/numpy-1.13.1-cp36-cp36m-manylinux1_x86_64.whl (17.0MB)
    100% |████████████████████████████████| 17.0MB 11.5MB/s
Collecting tushare==0.7.4 (from quantaxis==0.3.9b2.dev53)
  Downloading http://pypi.doubanio.com/packages/e6/86/ad0b88b85119292a4503a43355091988c25a234d0e89511b782464c4ff46/tushare-0.7.4.tar.gz (89kB)
    100% |████████████████████████████████| 92kB 13.6MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-mbu_8l9t/tushare/setup.py", line 4, in <module>
        import tushare
      File "/tmp/pip-build-mbu_8l9t/tushare/tushare/__init__.py", line 6, in <module>
        from tushare.stock.trading import (get_hist_data, get_tick_data,
      File "/tmp/pip-build-mbu_8l9t/tushare/tushare/stock/trading.py", line 13, in <module>
        import lxml.html
    ModuleNotFoundError: No module named 'lxml'
```

**Comment by rainx** [comment]
还有pandas 
```
Collecting tushare==0.7.4 (from quantaxis==0.3.9b2.dev53)
  Downloading http://pypi.doubanio.com/packages/e6/86/ad0b88b85119292a4503a43355091988c25a234d0e89511b782464c4ff46/tushare-0.7.4.tar.gz (89kB)
    100% |████████████████████████████████| 92kB 14.8MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-68tu_t9z/tushare/setup.py", line 4, in <module>
        import tushare
      File "/tmp/pip-build-68tu_t9z/tushare/tushare/__init__.py", line 6, in <module>
        from tushare.stock.trading import (get_hist_data, get_tick_data,
      File "/tmp/pip-build-68tu_t9z/tushare/tushare/stock/trading.py", line 15, in <module>
        import pandas as pd
    ModuleNotFoundError: No module named 'pandas'
```

**Comment by rainx** [comment]
晕，还有requests 
```
Collecting tushare==0.7.4 (from quantaxis==0.3.9b2.dev53)
  Downloading http://pypi.doubanio.com/packages/e6/86/ad0b88b85119292a4503a43355091988c25a234d0e89511b782464c4ff46/tushare-0.7.4.tar.gz (89kB)
    100% |████████████████████████████████| 92kB 9.6MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-zlte071g/tushare/setup.py", line 4, in <module>
        import tushare
      File "/tmp/pip-build-zlte071g/tushare/tushare/__init__.py", line 99, in <module>
        from tushare.trader.trader import TraderAPI
      File "/tmp/pip-build-zlte071g/tushare/tushare/trader/trader.py", line 12, in <module>
        import requests
    ModuleNotFoundError: No module named 'requests'
```

**Comment by yutiansut** [comment]
是的 tushare坑死我了

**Comment by yutiansut** [comment]
弄得我travis ci至今是failed

**Comment by yutiansut** [comment]
我好想pypi上的quantaxis没更新 得从github上下
pip install git+https://github.com/yutiansut/quantaxis

**Comment by yutiansut** [comment]
或者 这样  [https://github.com/yutiansut/QUANTAXIS#部署问题](https://github.com/yutiansut/QUANTAXIS#部署问题)
