### ISSUE TITLE
安装成功后，在import过程中出现“invalid syntax”

### ISSUE THREAD

**Issue by elisleaf** [yutiansut/QUANTAXIS#802]
import QUANTAXIS as QA
`QUANTAXIS>>` start QUANTAXIS
Traceback (most recent call last):

  File "E:\Anaconda3\envs\py35\lib\site-packages\IPython\core\interactiveshell.py", line 2961, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-5e05d327346f>", line 1, in <module>
    import QUANTAXIS as QA

  File "E:\Anaconda3\envs\py35\lib\site-packages\QUANTAXIS\__init__.py", line 57, in <module>
    from QUANTAXIS.QAFetch.Fetcher import QA_quotation  # 统一的获取接口

  File "E:\Anaconda3\envs\py35\lib\site-packages\QUANTAXIS\QAFetch\Fetcher.py", line 37, in <module>
    from QUANTAXIS.QAFetch import QAQuery_Async as QAQueryAsync

  File "E:\Anaconda3\envs\py35\lib\site-packages\QUANTAXIS\QAFetch\QAQuery_Async.py", line 64
    res = pd.DataFrame([item async for item in cursor])
                                 ^
SyntaxError: invalid syntax

**Comment by yutiansut** [comment]
3.5不支持3.6语法, 推荐升级3.6
