### ISSUE TITLE
版本问题与一个  Index' object has no attribute 'date'

### ISSUE THREAD

**Issue by Wier123** [yutiansut/QUANTAXIS#824]
大佬。新版本后就没提过ISSU。。。sorr。希望没发错ISSUE类型
1.现在版本更新很频繁。所以问下怎么显示自己当前版本和最新版本。？还是只要用之前就总是更新一下？
2.最新版更新后。我回测。显示
Traceback (most recent call last):
  File "D:\quant_strategy\QADEMO\QADemo-master\backtest\example\simple_backtest_daytt.py", line 193, in <module>
    risk = QA.QA_Risk(account=AC, benchmark_code=benchmark_code, benchmark_type=QA.MARKET_TYPE.INDEX_CN, if_fq=Fals
e)
  File "c:\quantaxis\QUANTAXIS\QAARP\QARisk.py", line 117, in __init__
    if self.market_value is not None:
  File "c:\quantaxis\QUANTAXIS\QAARP\QARisk.py", line 148, in market_value
    if self.account.daily_hold is not None:
  File "c:\quantaxis\QUANTAXIS\QAARP\QAAccount.py", line 399, in daily_hold
    date=data.index.levels[0].date)
AttributeError: 'Index' object has no attribute 'date'
PS C:\quantaxis\QUANTAXIS>

这问题以后是发issue还是群里问？

**Comment by Wier123** [comment]
。而且你知道我的。我除了example里的策略例子。其他地方我是不敢去改的。。。嗯

**Comment by yutiansut** [comment]
@Wier123 收到 这是我刚改的  我看下

**Comment by yutiansut** [comment]
https://github.com/QUANTAXIS/QUANTAXIS/pull/825

**Comment by yutiansut** [comment]
@Wier123  

```
git pull
```

**Comment by Wier123** [comment]
收到
