### ISSUE TITLE
可能属于bug类吧：ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by Wier123** [yutiansut/QUANTAXIS#826]
600193 2018-08-23 2018-08-20     100        2.83       2.73   0.036630       10.0

[73 rows x 7 columns]
Traceback (most recent call last):
  File "D:\quant_strategy\QADEMO\QADemo-master\backtest\example\simple_backtest_daytt.py", line 194, in <module>
    plt=risk.plot_assets_curve()
  File "c:\quantaxis\QUANTAXIS\QAARP\QARisk.py", line 496, in plot_assets_curve
    item, self.message[item]), fontsize=10, rotation=0, wrap=True)
  File "c:\quantaxis\QUANTAXIS\QAARP\QARisk.py", line 287, in message
    'ir': self.ir
  File "c:\quantaxis\QUANTAXIS\QAARP\QARisk.py", line 258, in ir
    return self.calc_IR()
  File "c:\quantaxis\QUANTAXIS\QAARP\QARisk.py", line 397, in calc_IR
    return self.annualize_return/self.volatility
ZeroDivisionError: float division by zero
PS C:\quantaxis\QUANTAXIS>

annualize_return是年化百分比收益（而且在QARisk.py的message里还保留两位）吧？
当好的策略收益好时。大于零。ok
当如果是一个bad的策略。收益差。就小于0。。就报错么？？

请教怎么解决。。谢谢

**Comment by yutiansut** [comment]
你这是波动率=0  这是没交易吗

**Comment by Wier123** [comment]
``有的。群给你了
