### ISSUE TITLE
KeyError: 'the label [2018-01-02 00:00:00] is not in the [index]'

### ISSUE THREAD

**Issue by Wier123** [yutiansut/QUANTAXIS#828]
刚更新了。是不是哪里index格式不对？？求解
Traceback (most recent call last):
  File "C:\Users\87532\AppData\Roaming\Python\Python36\site-packages\pandas\core\indexing.py", line 1790, in _valid
ate_key
    error()
  File "C:\Users\87532\AppData\Roaming\Python\Python36\site-packages\pandas\core\indexing.py", line 1785, in error
    axis=self.obj._get_axis_name(axis)))
KeyError: 'the label [2018-01-02 00:00:00] is not in the [index]'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\quant_strategy\QADEMO\QADemo-master\backtest\example\simple_backtest_daytt.py", line 169, in <module>
    simple_backtest(AC, backtest_code_list, backtest_start_date, backtest_end_date)
  File "D:\quant_strategy\QADEMO\QADemo-master\backtest\example\simple_backtest_daytt.py", line 53, in simple_backt
est
    cur_stock_signal = stock_signal.loc[cur_stock_date, cur_stock_code]
  File "C:\Users\87532\AppData\Roaming\Python\Python36\site-packages\pandas\core\indexing.py", line 1472, in __geti
tem__
    return self._getitem_tuple(key)
  File "C:\Users\87532\AppData\Roaming\Python\Python36\site-packages\pandas\core\indexing.py", line 870, in _getite
m_tuple
    return self._getitem_lowerdim(tup)
  File "C:\Users\87532\AppData\Roaming\Python\Python36\site-packages\pandas\core\indexing.py", line 998, in _getite
m_lowerdim
    section = self._getitem_axis(key, axis=i)
  File "C:\Users\87532\AppData\Roaming\Python\Python36\site-packages\pandas\core\indexing.py", line 1911, in _getit
em_axis
    self._validate_key(key, axis)
  File "C:\Users\87532\AppData\Roaming\Python\Python36\site-packages\pandas\core\indexing.py", line 1798, in _valid
ate_key
    error()
  File "C:\Users\87532\AppData\Roaming\Python\Python36\site-packages\pandas\core\indexing.py", line 1785, in error
    axis=self.obj._get_axis_name(axis)))
KeyError: 'the label [2018-01-02 00:00:00] is not in the [index]'
PS C:\quantaxis\QUANTAXIS> git pull
Already up to date.
PS C:\quantaxis\QUANTAXIS>

**Comment by yutiansut** [comment]
你传给我的文件我能跑通 @Wier123

**Comment by Wier123** [comment]
ok。知道问题是股票个数问题了。我转换一下自己策略的那个bb类型
